<?php
/**
 * Le Comptoir des Parfums — donnees produit (source unique).
 * 209 fiches : catalogue de la page d'accueil + pages parfum (template-parfum.php).
 * Genere depuis produits.js — garder les deux synchronises.
 *
 * Champs : s slug | b maison | n nom | pr prix | g genre | fam famille olfactive
 *          x concentration | t notes de tete | c notes de coeur | f notes de fond | d description
 *
 * Les pyramides olfactives suivent les compositions publiques connues de chaque
 * parfum : a relire maison par maison avant mise en ligne.
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

function comptoir_produits() {
	// Le tableau ci-dessous pese 72 Ko et PHP le reconstruit a chaque appel.
	// Or une seule page d'accueil appelle cette fonction une vingtaine de fois
	// (comptoir_selection() a elle seule la declenche neuf fois, via
	// comptoir_produit_by_slug). Un cache statique suffit : les donnees sont
	// litterales, elles ne changent pas d'un appel a l'autre.
	static $cache = null;
	if ( null !== $cache ) {
		return $cache;
	}
	$cache = array(
		array('s' => 'azzaro--forever-wanted-elixir', 'b' => 'Azzaro', 'n' => 'Forever Wanted Elixir', 'pr' => '389 DH', 'g' => 'Homme', 'fam' => 'Boisé fruité', 'x' => 'Eau de Parfum Intense', 't' => array('Framboise', 'Mandarine verte', 'Bergamote'), 'c' => array('Cardamome', 'Lavande', 'Sauge sclarée'), 'f' => array('Cuir', 'Vétiver', 'Bois'), 'd' => 'Une framboise vive sur la lavande et la cardamome, posée sur un fond de cuir et de vétiver : intense et élégant.'),
		array('s' => 'azzaro--the-most-wanted', 'b' => 'Azzaro', 'n' => 'The Most Wanted', 'pr' => '389 DH', 'g' => 'Homme', 'fam' => 'Ambré épicé', 'x' => 'Eau de Parfum Intense', 't' => array('Liqueur de gingembre', 'Cardamome'), 'c' => array('Toffee', 'Caramel'), 'f' => array('Bois ambré', 'Vétiver', 'Cèdre'), 'd' => 'Un gingembre liquoreux qui fond sur un caramel boisé, chaleureux et addictif.'),
		array('s' => 'burberry--goddess', 'b' => 'Burberry', 'n' => 'Goddess', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Ambré vanillé', 'x' => 'Eau de Parfum', 't' => array('Lavande', 'Gingembre'), 'c' => array('Vanille de Madagascar', 'Vanille caramel'), 'f' => array('Vanille absolue', 'Cacao'), 'd' => 'Trois vanilles superposées, adoucies d\'une lavande lactée et d\'un soupçon de cacao.'),
		array('s' => 'burberry--her-intense', 'b' => 'Burberry', 'n' => 'Her Intense', 'pr' => '339 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Cassis', 'Myrtille', 'Mûre'), 'c' => array('Jasmin', 'Fruits rouges'), 'f' => array('Ambre', 'Patchouli', 'Musc'), 'd' => 'Une bourrasque de fruits noirs sucrés sur un fond ambré et patchouli.'),
		array('s' => 'burberry--her-blossom', 'b' => 'Burberry', 'n' => 'Her Blossom', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Toilette', 't' => array('Mandarine', 'Poire'), 'c' => array('Pivoine', 'Jasmin', 'Fleur d\'oranger'), 'f' => array('Musc blanc', 'Bois blond'), 'd' => 'La fraise de Her éclaircie en bouquet printanier, plus légère et plus verte.'),
		array('s' => 'burberry--her-eau-de-parfum', 'b' => 'Burberry', 'n' => 'Her Eau de Parfum', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Fruits rouges', 'Cassis', 'Mûre'), 'c' => array('Jasmin', 'Violette'), 'f' => array('Musc', 'Patchouli', 'Bois de santal'), 'd' => 'Un panier de fruits rouges confits posé sur un musc profond, gourmand sans être sucré.'),
		array('s' => 'burberry--her-eau-de-toilette', 'b' => 'Burberry', 'n' => 'Her Eau de Toilette', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Toilette', 't' => array('Fruits rouges', 'Mandarine'), 'c' => array('Violette', 'Jasmin'), 'f' => array('Musc blanc', 'Bois de cèdre'), 'd' => 'La même gourmandise fruitée, en version claire, pour la journée.'),
		array('s' => 'carolina-herrera--good-girl-blush', 'b' => 'Carolina Herrera', 'n' => 'Good Girl Blush', 'pr' => '389 DH', 'g' => 'Femme', 'fam' => 'Floral ambré', 'x' => 'Eau de Parfum', 't' => array('Amande', 'Bergamote'), 'c' => array('Fleur d\'oranger', 'Ylang-ylang', 'Jasmin sambac'), 'f' => array('Bois ambré', 'Vétiver', 'Vanille'), 'd' => 'Une fleur d\'oranger solaire posée sur une amande crémeuse et des bois clairs.'),
		array('s' => 'chanel--allure-homme-sport', 'b' => 'Chanel', 'n' => 'Allure Homme Sport', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Boisé aromatique', 'x' => 'Eau de Toilette', 't' => array('Orange', 'Notes marines', 'Poivre'), 'c' => array('Néroli', 'Cèdre'), 'f' => array('Musc blanc', 'Tonka', 'Vétiver'), 'd' => 'Un boisé net et lumineux, agrumes et poivre sur un sillage musqué discret.'),
		array('s' => 'chanel--bleu-de-chanel-lexclusif', 'b' => 'Chanel', 'n' => 'Bleu de Chanel L\'Exclusif', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Boisé aromatique', 'x' => 'Parfum', 't' => array('Citron', 'Menthe', 'Poivre rose'), 'c' => array('Encens', 'Gingembre', 'Jasmin'), 'f' => array('Santal', 'Cèdre', 'Fève tonka'), 'd' => 'La signature Bleu poussée à son maximum : encens, santal et tonka très concentrés.'),
		array('s' => 'chanel--bleu-de-chanel-parfum', 'b' => 'Chanel', 'n' => 'Bleu de Chanel Parfum', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Boisé aromatique', 'x' => 'Parfum', 't' => array('Citron', 'Menthe', 'Poivre rose'), 'c' => array('Labdanum', 'Gingembre', 'Jasmin'), 'f' => array('Santal', 'Cèdre', 'Patchouli', 'Fève tonka'), 'd' => 'Un boisé-aromatique profond et enveloppant, santal crémeux et fond tonka.'),
		array('s' => 'chanel--chance-eau-fraiche', 'b' => 'Chanel', 'n' => 'Chance Eau Fraîche', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Chypré floral', 'x' => 'Eau de Toilette', 't' => array('Citron', 'Cédrat'), 'c' => array('Jacinthe d\'eau', 'Jasmin'), 'f' => array('Bois de teck', 'Patchouli', 'Ambre'), 'd' => 'La version la plus verte et vive de Chance, agrumes fusants sur bois clair.'),
		array('s' => 'chanel--chance-eau-tendre', 'b' => 'Chanel', 'n' => 'Chance Eau Tendre', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Pamplemousse', 'Coing'), 'c' => array('Jasmin', 'Jacinthe'), 'f' => array('Musc blanc', 'Iris', 'Cèdre'), 'd' => 'Un floral-fruité tendre et poudré, pamplemousse juteux et musc soyeux.'),
		array('s' => 'chanel--coco-mademoiselle', 'b' => 'Chanel', 'n' => 'Coco Mademoiselle', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Chypré floral', 'x' => 'Eau de Parfum', 't' => array('Orange', 'Bergamote', 'Mandarine'), 'c' => array('Rose', 'Jasmin', 'Litchi'), 'f' => array('Patchouli', 'Vétiver', 'Musc blanc', 'Vanille'), 'd' => 'Le chypré moderne par excellence : rose vive, patchouli net, sillage insolent.'),
		array('s' => 'chanel--coco-noir', 'b' => 'Chanel', 'n' => 'Coco Noir', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Oriental ambré', 'x' => 'Eau de Parfum', 't' => array('Pamplemousse', 'Bergamote'), 'c' => array('Rose', 'Narcisse', 'Jasmin'), 'f' => array('Patchouli', 'Santal', 'Fève tonka', 'Encens'), 'd' => 'Un oriental sombre et satiné, fleurs enrobées de patchouli et d\'encens.'),
		array('s' => 'chanel--n-5-eau-de-parfum', 'b' => 'Chanel', 'n' => 'N°5 Eau de Parfum', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Floral aldéhydé', 'x' => 'Eau de Parfum', 't' => array('Aldéhydes', 'Ylang-ylang', 'Néroli'), 'c' => array('Rose de Mai', 'Jasmin', 'Iris'), 'f' => array('Santal', 'Vétiver', 'Vanille', 'Ambre'), 'd' => 'Le bouquet abstrait le plus célèbre au monde, aldéhydes et fleurs blanches poudrées.'),
		array('s' => 'chanel--chance-eau-de-parfum', 'b' => 'Chanel', 'n' => 'Chance Eau de Parfum', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral ambré', 'x' => 'Eau de Parfum', 't' => array('Poivre rose', 'Citron'), 'c' => array('Jasmin', 'Iris'), 'f' => array('Patchouli', 'Vanille', 'Vétiver', 'Ambre'), 'd' => 'Le poivre rose de Chance sur un fond vanillé plus dense que les Eaux : la version du soir.'),
		array('s' => 'chanel--coco-mademoiselle-leau-privee', 'b' => 'Chanel', 'n' => 'Coco Mademoiselle L\'Eau Privée', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral musqué', 'x' => 'Eau pour la nuit', 't' => array('Orange', 'Bergamote'), 'c' => array('Rose', 'Jasmin'), 'f' => array('Musc blanc', 'Patchouli'), 'd' => 'Coco Mademoiselle mise en sourdine : le patchouli recule, le musc reste. Faite pour la peau, pas pour la pièce.'),
		array('s' => 'chloe--love-story', 'b' => 'Chloé', 'n' => 'Love Story', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral', 'x' => 'Eau de Parfum', 't' => array('Néroli', 'Bergamote'), 'c' => array('Fleur d\'oranger', 'Jasmin', 'Rose'), 'f' => array('Cèdre', 'Musc'), 'd' => 'Un floral blanc lumineux et propre, fleur d\'oranger sur un fond de cèdre doux.'),
		array('s' => 'chloe--eau-de-parfum', 'b' => 'Chloé', 'n' => 'Eau de Parfum', 'pr' => '389 DH', 'g' => 'Femme', 'fam' => 'Floral poudré', 'x' => 'Eau de Parfum', 't' => array('Pivoine', 'Litchi', 'Freesia'), 'c' => array('Rose', 'Magnolia', 'Muguet'), 'f' => array('Ambre', 'Cèdre', 'Musc'), 'd' => 'La rose propre et poudrée, celle du savon de luxe, tenue par un ambre discret.'),
		array('s' => 'creed--absolu-aventus', 'b' => 'Creed', 'n' => 'Absolu Aventus', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Chypré ambré', 'x' => 'Eau de Parfum', 't' => array('Ananas', 'Bergamote', 'Cassis'), 'c' => array('Patchouli', 'Encens', 'Iris'), 'f' => array('Ambre gris', 'Vanille', 'Fève tonka', 'Musc'), 'd' => 'Un Aventus plus dense et résineux, l\'ananas signature enrobé d\'ambre et de vanille.'),
		array('s' => 'creed--aventus', 'b' => 'Creed', 'n' => 'Aventus', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Chypré fruité', 'x' => 'Eau de Parfum', 't' => array('Ananas', 'Bergamote', 'Cassis', 'Pomme'), 'c' => array('Bouleau', 'Patchouli', 'Rose', 'Jasmin'), 'f' => array('Mousse de chêne', 'Musc', 'Ambre gris', 'Vanille'), 'd' => 'L\'ananas fumé le plus copié de la parfumerie, viril, fruité et minéral.'),
		array('s' => 'creed--viking', 'b' => 'Creed', 'n' => 'Viking', 'pr' => '389 DH', 'g' => 'Homme', 'fam' => 'Aromatique épicé', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Menthe poivrée', 'Poivre rose'), 'c' => array('Lavande', 'Poivre du Sichuan', 'Rose'), 'f' => array('Vétiver', 'Santal', 'Patchouli', 'Cèdre'), 'd' => 'Une menthe poivrée franche qui cède à un vétiver sec : nerveux, frais, viril.'),
		array('s' => 'dior--ambre-nuit-esprit-de-parfum', 'b' => 'Dior', 'n' => 'Ambre Nuit Esprit De Parfum', 'pr' => '419 DH', 'g' => 'Mixte', 'fam' => 'Ambré épicé', 'x' => 'Esprit de Parfum', 't' => array('Bergamote', 'Pamplemousse', 'Poivre rose'), 'c' => array('Rose de Taïf'), 'f' => array('Ambre gris', 'Patchouli', 'Bois de gaïac'), 'd' => 'Une rose épicée qui se dissout dans un ambre gris minéral et fumé.'),
		array('s' => 'dior--dior-homme-intense', 'b' => 'Dior', 'n' => 'Dior Homme Intense', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Floral boisé', 'x' => 'Eau de Parfum', 't' => array('Lavande'), 'c' => array('Iris', 'Ambrette'), 'f' => array('Cèdre de Virginie', 'Vétiver', 'Cacao'), 'd' => 'Un iris poudré, presque maquillage, tenu par un cèdre profond et un fil de cacao.'),
		array('s' => 'dior--fahrenheit-le-parfum', 'b' => 'Dior', 'n' => 'Fahrenheit Le Parfum', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Boisé épicé', 'x' => 'Parfum', 't' => array('Mandarine', 'Feuille de violette'), 'c' => array('Encens', 'Réglisse'), 'f' => array('Fève tonka', 'Cuir', 'Styrax', 'Vétiver'), 'd' => 'La violette pétrole de Fahrenheit rendue plus fumée, cuirée et résineuse.'),
		array('s' => 'dior--hypnotic-poison-edp', 'b' => 'Dior', 'n' => 'Hypnotic Poison EDP', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Ambré vanillé', 'x' => 'Eau de Parfum', 't' => array('Noix de coco', 'Prune', 'Abricot'), 'c' => array('Jasmin', 'Rose', 'Muguet', 'Carvi'), 'f' => array('Amande', 'Vanille', 'Musc', 'Santal'), 'd' => 'Une amande-vanille hypnotique et lactée, sombre et enveloppante à la fois.'),
		array('s' => 'dior--joy-by-dior-intense', 'b' => 'Dior', 'n' => 'Joy by Dior Intense', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral boisé', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Mandarine'), 'c' => array('Rose de Grasse', 'Jasmin', 'Magnolia'), 'f' => array('Santal', 'Musc blanc', 'Patchouli'), 'd' => 'Un bouquet de Grasse éclatant, adouci d\'un santal crémeux et de musc.'),
		array('s' => 'dior--miss-dior-eau-de-parfum', 'b' => 'Dior', 'n' => 'Miss Dior Eau de Parfum', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Floral', 'x' => 'Eau de Parfum', 't' => array('Poivre rose', 'Notes vertes'), 'c' => array('Rose de Grasse', 'Pivoine', 'Muguet'), 'f' => array('Bois de rose', 'Musc blanc'), 'd' => 'Un cœur de rose fraîche et de pivoine, moderne, propre et lumineux.'),
		array('s' => 'dior--miss-dior-parfum', 'b' => 'Dior', 'n' => 'Miss Dior Parfum', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Floral ambré', 'x' => 'Parfum', 't' => array('Rose de Grasse'), 'c' => array('Tubéreuse', 'Fleur d\'oranger', 'Iris'), 'f' => array('Santal', 'Vanille', 'Musc'), 'd' => 'La rose de Miss Dior alourdie de tubéreuse et posée sur un fond vanillé.'),
		array('s' => 'dior--miss-dior-rose-essence', 'b' => 'Dior', 'n' => 'Miss Dior Rose Essence', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Floral rosé', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Notes vertes'), 'c' => array('Rose de Grasse', 'Géranium'), 'f' => array('Musc blanc', 'Bois blond'), 'd' => 'Une rose verte, mordante, coupée dans le jardin au petit matin.'),
		array('s' => 'dior--oud-ispahan-esprit-de-parfum', 'b' => 'Dior', 'n' => 'Oud Ispahan Esprit De Parfum', 'pr' => '419 DH', 'g' => 'Mixte', 'fam' => 'Boisé oriental', 'x' => 'Esprit de Parfum', 't' => array('Rose', 'Safran'), 'c' => array('Oud', 'Labdanum'), 'f' => array('Santal', 'Patchouli', 'Cuir'), 'd' => 'Une rose sombre et un oud fumé, opulents, presque liturgiques.'),
		array('s' => 'dior--sauvage-eau-de-parfum', 'b' => 'Dior', 'n' => 'Sauvage Eau de Parfum', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Aromatique ambré', 'x' => 'Eau de Parfum', 't' => array('Bergamote de Calabre', 'Poivre de Sichuan'), 'c' => array('Lavande', 'Anis étoilé', 'Muscade'), 'f' => array('Ambroxan', 'Vanille'), 'd' => 'La lavande-ambroxan de Sauvage rendue plus douce, ronde et vanillée.'),
		array('s' => 'dior--sauvage-elixir', 'b' => 'Dior', 'n' => 'Sauvage Elixir', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Aromatique épicé', 'x' => 'Elixir', 't' => array('Pamplemousse', 'Cannelle', 'Cardamome', 'Muscade'), 'c' => array('Lavande', 'Réglisse'), 'f' => array('Santal', 'Patchouli', 'Ambre', 'Vanille'), 'd' => 'Une concentration dense et poivrée, lavande liquoreuse sur bois profonds.'),
		array('s' => 'dior--sauvage-parfum', 'b' => 'Dior', 'n' => 'Sauvage Parfum', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Ambré boisé', 'x' => 'Parfum', 't' => array('Bergamote', 'Mandarine'), 'c' => array('Lavande', 'Santal'), 'f' => array('Fève tonka', 'Ambroxan', 'Vanille', 'Cèdre'), 'd' => 'La face la plus chaude de Sauvage : tonka, santal et vanille, sillage sourd.'),
		array('s' => 'dior--dior-addict', 'b' => 'Dior', 'n' => 'Dior Addict', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral boisé musqué', 'x' => 'Eau de Parfum', 't' => array('Mandarine', 'Bergamote'), 'c' => array('Jasmin sambac', 'Fleur d\'oranger'), 'f' => array('Bois de santal', 'Vanille', 'Musc'), 'd' => 'Un jasmin sambac lumineux sur un santal vanillé, glamour sans excès.'),
		array('s' => 'dior--dior-addict-eau-fraiche', 'b' => 'Dior', 'n' => 'Dior Addict Eau Fraîche', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral frais', 'x' => 'Eau Fraîche', 't' => array('Bergamote', 'Mandarine'), 'c' => array('Rose', 'Jasmin'), 'f' => array('Musc blanc', 'Cèdre'), 'd' => 'Addict passé à l\'eau claire : les fleurs restent, le sucre s\'en va.'),
		array('s' => 'dior--dior-homme-parfum', 'b' => 'Dior', 'n' => 'Dior Homme Parfum', 'pr' => '389 DH', 'g' => 'Homme', 'fam' => 'Boisé iris', 'x' => 'Parfum', 't' => array('Iris'), 'c' => array('Iris poudré', 'Cuir'), 'f' => array('Cèdre', 'Santal', 'Vétiver', 'Musc'), 'd' => 'L\'iris le plus élégant de la parfumerie masculine, poudré, cuiré, presque maquillage.'),
		array('s' => 'dior--miss-dior-absolutely-blooming', 'b' => 'Dior', 'n' => 'Miss Dior Absolutely Blooming', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Baies rouges', 'Mandarine'), 'c' => array('Rose de Damas', 'Pivoine'), 'f' => array('Musc blanc'), 'd' => 'Des baies rouges croquantes sur une rose de Damas : la version la plus juteuse de Miss Dior.'),
		array('s' => 'dior--miss-dior-blooming-bouquet', 'b' => 'Dior', 'n' => 'Miss Dior Blooming Bouquet', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral tendre', 'x' => 'Eau de Toilette', 't' => array('Mandarine de Sicile'), 'c' => array('Pivoine', 'Rose de Damas', 'Abricot'), 'f' => array('Musc blanc'), 'd' => 'Une pivoine tendre et une pêche à peine mûre, le Miss Dior le plus doux.'),
		array('s' => 'dior--poison-girl', 'b' => 'Dior', 'n' => 'Poison Girl', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Ambré gourmand', 'x' => 'Eau de Parfum', 't' => array('Orange sanguine', 'Citron de Sicile'), 'c' => array('Rose de Grasse', 'Rose de Damas', 'Fleur d\'oranger'), 'f' => array('Amande', 'Vanille', 'Fève tonka'), 'd' => 'Une amande sucrée enroulée autour de la rose : Poison en version dragée, sombre et ronde.'),
		array('s' => 'dolce-gabbana--devotion-pour-homme', 'b' => 'Dolce & Gabbana', 'n' => 'Devotion Pour Homme', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Ambré gourmand', 'x' => 'Eau de Parfum', 't' => array('Cédrat', 'Bergamote', 'Poivre'), 'c' => array('Accord panettone', 'Café'), 'f' => array('Vanille', 'Fève tonka', 'Bois ambré'), 'd' => 'Un agrume vif qui glisse vers un accord brioché et un café vanillé.'),
		array('s' => 'dolce-gabbana--king-edt', 'b' => 'Dolce & Gabbana', 'n' => 'King EDT', 'pr' => '359 DH', 'g' => 'Homme', 'fam' => 'Aromatique fougère', 'x' => 'Eau de Toilette', 't' => array('Orange sanguine', 'Citron', 'Genièvre'), 'c' => array('Piment', 'Sauge', 'Géranium'), 'f' => array('Cèdre', 'Patchouli', 'Vétiver'), 'd' => 'Une fougère solaire et virile, agrumes juteux sur bois secs et vétiver.'),
		array('s' => 'dolce-gabbana--limperatrice-royale', 'b' => 'Dolce & Gabbana', 'n' => 'L\'Imperatrice Royale', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Fruité floral', 'x' => 'Eau de Parfum', 't' => array('Pastèque', 'Fruits rouges'), 'c' => array('Jasmin', 'Fleurs blanches'), 'f' => array('Musc', 'Ambre'), 'd' => 'La pastèque culte de L\'Imperatrice, plus dense, plus florale, plus tenace.'),
		array('s' => 'dolce-gabbana--light-blue-capri-in-love', 'b' => 'Dolce & Gabbana', 'n' => 'Light Blue Capri In Love', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Hespéridé fruité', 'x' => 'Eau de Parfum', 't' => array('Citron de Sicile', 'Pomme Granny Smith'), 'c' => array('Jasmin', 'Rose blanche'), 'f' => array('Cèdre', 'Ambre', 'Musc'), 'd' => 'Le Light Blue de toujours, un cran plus mûr et plus enveloppant.'),
		array('s' => 'dolce-gabbana--light-blue-eau-de-toilette', 'b' => 'Dolce & Gabbana', 'n' => 'Light Blue Eau de Toilette', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Hespéridé fruité', 'x' => 'Eau de Toilette', 't' => array('Citron de Sicile', 'Pomme', 'Cloche de bruyère'), 'c' => array('Bambou', 'Jasmin', 'Rose blanche'), 'f' => array('Cèdre', 'Ambre', 'Musc'), 'd' => 'Le parfum de l\'été méditerranéen : citron, pomme verte, bois blond.'),
		array('s' => 'dolce-gabbana--light-blue-pour-homme-edt', 'b' => 'Dolce & Gabbana', 'n' => 'Light Blue Pour Homme EDT', 'pr' => '359 DH', 'g' => 'Homme', 'fam' => 'Hespéridé aromatique', 'x' => 'Eau de Toilette', 't' => array('Pamplemousse', 'Bergamote', 'Mandarine'), 'c' => array('Poivre', 'Bois de rose', 'Genièvre'), 'f' => array('Musc', 'Mousse de chêne', 'Encens'), 'd' => 'La version masculine du Light Blue, agrumes frais sur bois poivrés.'),
		array('s' => 'dolce-gabbana--my-devotion-edp-intense', 'b' => 'Dolce & Gabbana', 'n' => 'My Devotion EDP Intense', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Gourmand vanillé', 'x' => 'Eau de Parfum Intense', 't' => array('Cédrat', 'Bergamote'), 'c' => array('Accord panettone', 'Fleur d\'oranger'), 'f' => array('Vanille', 'Fève tonka', 'Bois de cachemire'), 'd' => 'Un dessert italien en flacon : brioche confite, fleur d\'oranger et vanille.'),
		array('s' => 'dolce-gabbana--q-by-dolce-gabbana', 'b' => 'Dolce & Gabbana', 'n' => 'Q by Dolce & Gabbana', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Fruité floral', 'x' => 'Eau de Parfum', 't' => array('Bergamote de Calabre', 'Cerise griotte'), 'c' => array('Jasmin', 'Héliotrope'), 'f' => array('Cèdre', 'Musc'), 'd' => 'Une griotte acidulée et pulpeuse sur un cœur de jasmin, jeune et vibrant.'),
		array('s' => 'elie-saab--girl-of-now', 'b' => 'Elie Saab', 'n' => 'Girl of Now', 'pr' => '389 DH', 'g' => 'Femme', 'fam' => 'Floral gourmand', 'x' => 'Eau de Parfum', 't' => array('Poire', 'Mandarine', 'Amande'), 'c' => array('Fleur d\'oranger', 'Jasmin'), 'f' => array('Pistache', 'Patchouli', 'Fève tonka'), 'd' => 'La pistache et l\'amande en pâtisserie orientale, adoucies de fleur d\'oranger.'),
		array('s' => 'emporio-armani--stronger-with-you-absolutely', 'b' => 'Emporio Armani', 'n' => 'Stronger With You Absolutely', 'pr' => '309 DH', 'g' => 'Homme', 'fam' => 'Ambré épicé', 'x' => 'Parfum', 't' => array('Poivre rose', 'Violette'), 'c' => array('Café', 'Toffee'), 'f' => array('Vanille', 'Bois ambré'), 'd' => 'La face la plus intense de la ligne : café amer, toffee et bois ambré.'),
		array('s' => 'emporio-armani--stronger-with-you-amber-edp', 'b' => 'Emporio Armani', 'n' => 'Stronger With You Amber EDP', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Ambré', 'x' => 'Eau de Parfum', 't' => array('Cardamome', 'Bergamote'), 'c' => array('Ambre', 'Miel'), 'f' => array('Vanille', 'Châtaigne'), 'd' => 'Un ambre miellé et chaud, cardamome en tête, châtaigne grillée en fond.'),
		array('s' => 'emporio-armani--stronger-with-you-intensely', 'b' => 'Emporio Armani', 'n' => 'Stronger With You Intensely', 'pr' => '359 DH', 'g' => 'Homme', 'fam' => 'Ambré aromatique', 'x' => 'Eau de Parfum', 't' => array('Poivre rose', 'Genièvre', 'Violette'), 'c' => array('Toffee', 'Cannelle', 'Lavande'), 'f' => array('Vanille', 'Fève tonka', 'Bois ambré'), 'd' => 'Le Stronger With You de base épaissi de toffee, de cannelle et de tonka.'),
		array('s' => 'emporio-armani--stronger-with-you-oud-edp', 'b' => 'Emporio Armani', 'n' => 'Stronger With You Oud EDP', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Boisé oriental', 'x' => 'Eau de Parfum', 't' => array('Safran', 'Cardamome'), 'c' => array('Oud', 'Ambre'), 'f' => array('Vanille', 'Châtaigne'), 'd' => 'Un oud sage et propre, safran en tête, vanille-châtaigne pour l\'arrondir.'),
		array('s' => 'emporio-armani--stronger-with-you-parfum', 'b' => 'Emporio Armani', 'n' => 'Stronger With You Parfum', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Ambré boisé', 'x' => 'Parfum', 't' => array('Feuille de violette', 'Cardamome', 'Sauge'), 'c' => array('Châtaigne', 'Fève tonka'), 'f' => array('Vanille', 'Suède', 'Bois ambré'), 'd' => 'La version parfum, plus sèche et plus boisée, châtaigne et suède.'),
		array('s' => 'emporio-armani--stronger-with-you-sandalwood', 'b' => 'Emporio Armani', 'n' => 'Stronger With You Sandalwood', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Boisé', 'x' => 'Eau de Parfum', 't' => array('Cardamome', 'Bergamote'), 'c' => array('Santal'), 'f' => array('Vanille', 'Fève tonka', 'Châtaigne'), 'd' => 'Un santal crémeux au centre, encadré de cardamome et de vanille douce.'),
		array('s' => 'emporio-armani--stronger-with-you-tobacco', 'b' => 'Emporio Armani', 'n' => 'Stronger With You Tobacco', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Ambré tabac', 'x' => 'Eau de Parfum', 't' => array('Cardamome', 'Poivre rose'), 'c' => array('Tabac', 'Châtaigne'), 'f' => array('Vanille', 'Fève tonka', 'Bois ambré'), 'd' => 'Un tabac miellé et gourmand, doux plutôt que sombre, sur base vanillée.'),
		array('s' => 'giardini-di-toscana--bianco-latte', 'b' => 'Giardini di Toscana', 'n' => 'Bianco Latte', 'pr' => '519 DH', 'g' => 'Mixte', 'fam' => 'Gourmand lacté', 'x' => 'Extrait de Parfum', 't' => array('Lait', 'Sucre'), 'c' => array('Caramel', 'Musc blanc'), 'f' => array('Vanille', 'Fève tonka'), 'd' => 'Un accord lait-sucre réconfortant, comme une peau propre et sucrée.'),
		array('s' => 'giorgio-armani--acqua-di-gio-edp', 'b' => 'Giorgio Armani', 'n' => 'Acqua di Giò EDP', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Aromatique aquatique', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Mandarine verte', 'Notes marines'), 'c' => array('Romarin', 'Jasmin', 'Géranium'), 'f' => array('Patchouli', 'Cèdre', 'Encens'), 'd' => 'L\'aquatique de référence rendu plus profond, sel marin sur bois et encens.'),
		array('s' => 'giorgio-armani--armani-prive-bleu-lazuli-edp', 'b' => 'Giorgio Armani', 'n' => 'Armani Privé — Bleu Lazuli EDP', 'pr' => '369 DH', 'g' => 'Mixte', 'fam' => 'Ambré épicé', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Cardamome', 'Poivre rose'), 'c' => array('Fleur d\'oranger'), 'f' => array('Benjoin', 'Vanille', 'Fève tonka', 'Cèdre'), 'd' => 'Une fleur d\'oranger épicée et solaire posée sur un benjoin ambré.'),
		array('s' => 'giorgio-armani--armani-prive-rouge-malachite', 'b' => 'Giorgio Armani', 'n' => 'Armani Prive Rouge Malachite', 'pr' => '369 DH', 'g' => 'Mixte', 'fam' => 'Boisé aromatique', 'x' => 'Eau de Parfum', 't' => array('Mandarine verte', 'Cardamome', 'Poivre rose'), 'c' => array('Néroli', 'Patchouli'), 'f' => array('Benjoin', 'Musc', 'Bois ambré'), 'd' => 'Un boisé vert et vif, agrumes croquants sur patchouli net et benjoin.'),
		array('s' => 'giorgio-armani--my-way-edp', 'b' => 'Giorgio Armani', 'n' => 'My Way EDP', 'pr' => '339 DH', 'g' => 'Femme', 'fam' => 'Floral', 'x' => 'Eau de Parfum', 't' => array('Fleur d\'oranger', 'Bergamote'), 'c' => array('Tubéreuse', 'Jasmin indien'), 'f' => array('Musc blanc', 'Vanille de Madagascar', 'Cèdre'), 'd' => 'Un floral blanc moderne et clair, fleur d\'oranger et tubéreuse sur musc.'),
		array('s' => 'giorgio-armani--my-way-intense', 'b' => 'Giorgio Armani', 'n' => 'My Way Intense', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Floral ambré', 'x' => 'Eau de Parfum Intense', 't' => array('Fleur d\'oranger', 'Bergamote'), 'c' => array('Tubéreuse', 'Jasmin'), 'f' => array('Vanille', 'Fève tonka', 'Santal'), 'd' => 'Le My Way de base réchauffé de vanille et de tonka, plus sensuel le soir.'),
		array('s' => 'giorgio-armani--my-way-ylang', 'b' => 'Giorgio Armani', 'n' => 'My Way Ylang', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral', 'x' => 'Eau de Parfum', 't' => array('Ylang-ylang', 'Bergamote'), 'c' => array('Fleur d\'oranger', 'Tubéreuse'), 'f' => array('Vanille', 'Musc blanc'), 'd' => 'Une variation autour de l\'ylang-ylang, crémeuse et légèrement banane-fleurie.'),
		array('s' => 'giorgio-armani--si-fiori', 'b' => 'Giorgio Armani', 'n' => 'Sì Fiori', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral chypré', 'x' => 'Eau de Parfum', 't' => array('Néroli', 'Bergamote', 'Cassis'), 'c' => array('Rose', 'Freesia', 'Muguet'), 'f' => array('Vanille', 'Ambroxan', 'Bois blond'), 'd' => 'La version la plus fleurie de Sì, rose et néroli sur fond de cassis.'),
		array('s' => 'giorgio-armani--si-parfum', 'b' => 'Giorgio Armani', 'n' => 'Sì Parfum', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Chypré fruité', 'x' => 'Parfum', 't' => array('Nectar de cassis'), 'c' => array('Rose', 'Freesia'), 'f' => array('Vanille', 'Patchouli', 'Bois ambré'), 'd' => 'Le cassis liquoreux de Sì concentré à l\'extrême, rond et patchouli.'),
		array('s' => 'giorgio-armani--si-passione', 'b' => 'Giorgio Armani', 'n' => 'Sì Passione', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Poire', 'Cassis', 'Bergamote'), 'c' => array('Rose', 'Jasmin', 'Héliotrope'), 'f' => array('Vanille', 'Cèdre', 'Patchouli'), 'd' => 'Un floral-fruité vibrant, rose éclatante sur poire juteuse et vanille.'),
		array('s' => 'giorgio-armani--si-passione-eclat-de-parfum', 'b' => 'Giorgio Armani', 'n' => 'Sì Passione Éclat de Parfum', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Framboise', 'Poire', 'Poivre rose'), 'c' => array('Rose', 'Jasmin', 'Pivoine'), 'f' => array('Vanille', 'Bois blond'), 'd' => 'Sì Passione en plus pétillant, framboise acidulée et pivoine fraîche.'),
		array('s' => 'giorgio-armani--acqua-di-gio-parfum', 'b' => 'Giorgio Armani', 'n' => 'Acqua di Giò Parfum', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Aromatique marin', 'x' => 'Parfum', 't' => array('Bergamote', 'Notes marines'), 'c' => array('Sauge', 'Géranium', 'Patchouli'), 'f' => array('Encens', 'Cèdre', 'Ambre gris'), 'd' => 'Le marin d\'Acqua di Giò assombri d\'encens : la mer à la nuit tombée.'),
		array('s' => 'giorgio-armani--si-passione-red-musk', 'b' => 'Giorgio Armani', 'n' => 'Sì Passione Red Musk', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral fruité musqué', 'x' => 'Eau de Parfum', 't' => array('Poire', 'Cassis'), 'c' => array('Rose', 'Freesia'), 'f' => array('Musc rouge', 'Vanille', 'Bois ambré'), 'd' => 'Le cassis de Sì rougi par un musc épais et chaud, plus charnel que l\'original.'),
		array('s' => 'givenchy--gentleman-reserve-privee', 'b' => 'Givenchy', 'n' => 'Gentleman Réserve Privée', 'pr' => '379 DH', 'g' => 'Homme', 'fam' => 'Boisé ambré', 'x' => 'Eau de Parfum', 't' => array('Cardamome noire', 'Bergamote'), 'c' => array('Vanille bourbon', 'Cacao'), 'f' => array('Cuir', 'Santal', 'Patchouli'), 'd' => 'Une vanille bourbon fumée, cacao amer et cuir, sombre et distinguée.'),
		array('s' => 'givenchy--irresistible-edt', 'b' => 'Givenchy', 'n' => 'Irresistible EDT', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Toilette', 't' => array('Poire', 'Bergamote'), 'c' => array('Rose', 'Iris'), 'f' => array('Bois blond', 'Musc'), 'd' => 'Une rose fraîche et une poire croquante, propres et faciles à porter.'),
		array('s' => 'givenchy--linterdit-absolu-edp-intense', 'b' => 'Givenchy', 'n' => 'L\'Interdit Absolu EDP Intense', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral ambré', 'x' => 'Eau de Parfum Intense', 't' => array('Fleur d\'oranger', 'Bergamote'), 'c' => array('Tubéreuse', 'Jasmin'), 'f' => array('Vanille', 'Fève tonka', 'Santal'), 'd' => 'Les fleurs blanches de L\'Interdit alourdies de vanille et de tonka.'),
		array('s' => 'givenchy--linterdit-edp-rouge', 'b' => 'Givenchy', 'n' => 'L\'Interdit EDP Rouge', 'pr' => '319 DH', 'g' => 'Femme', 'fam' => 'Floral épicé', 'x' => 'Eau de Parfum', 't' => array('Orange sanguine', 'Gingembre'), 'c' => array('Tubéreuse', 'Lys ginger', 'Cannelle'), 'f' => array('Patchouli', 'Encens', 'Benjoin'), 'd' => 'Une tubéreuse mordue de gingembre et de cannelle, chaude et un peu vénéneuse.'),
		array('s' => 'givenchy--linterdit-edp-rouge-ultime', 'b' => 'Givenchy', 'n' => 'L\'Interdit EDP Rouge Ultime', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral épicé ambré', 'x' => 'Eau de Parfum', 't' => array('Safran', 'Orange sanguine'), 'c' => array('Tubéreuse', 'Cannelle'), 'f' => array('Patchouli', 'Encens', 'Benjoin'), 'd' => 'L\'Interdit Rouge poussé plus loin, safran et encens sur fleurs incandescentes.'),
		array('s' => 'givenchy--linterdit-tubereuse-noire', 'b' => 'Givenchy', 'n' => 'L\'Interdit Tubéreuse Noire', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral capiteux', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Poivre noir'), 'c' => array('Tubéreuse', 'Jasmin'), 'f' => array('Bois noirs', 'Encens', 'Patchouli'), 'd' => 'Une tubéreuse sombre et résineuse, presque nocturne, sur bois fumés.'),
		array('s' => 'gucci--flora-gorgeous-gardenia', 'b' => 'Gucci', 'n' => 'Flora Gorgeous Gardenia', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Poire', 'Fleur de gardénia'), 'c' => array('Gardénia', 'Frangipanier'), 'f' => array('Sucre brun', 'Patchouli'), 'd' => 'Un gardénia sucré et poudré, très féminin, sur une pointe de sucre brun.'),
		array('s' => 'gucci--flora-gorgeous-gardenia-intense', 'b' => 'Gucci', 'n' => 'Flora Gorgeous Gardenia Intense', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral ambré', 'x' => 'Eau de Parfum Intense', 't' => array('Poire', 'Poivre rose'), 'c' => array('Gardénia', 'Ylang-ylang'), 'f' => array('Vanille', 'Patchouli', 'Musc'), 'd' => 'Le Gardenia rendu plus dense et plus vanillé, sillage réchauffé.'),
		array('s' => 'gucci--flora-gorgeous-jasmine', 'b' => 'Gucci', 'n' => 'Flora Gorgeous Jasmine', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral', 'x' => 'Eau de Parfum', 't' => array('Mandarine', 'Poivre rose'), 'c' => array('Jasmin', 'Fleur d\'oranger'), 'f' => array('Bois de santal', 'Musc'), 'd' => 'Un jasmin clair et pétillant, jamais lourd, sur un fond de santal doux.'),
		array('s' => 'gucci--flora-gorgeous-magnolia', 'b' => 'Gucci', 'n' => 'Flora Gorgeous Magnolia', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Cassis', 'Bergamote'), 'c' => array('Magnolia', 'Néroli'), 'f' => array('Musc', 'Bois blond'), 'd' => 'Un magnolia frais et fruité de cassis, jeune et lumineux.'),
		array('s' => 'gucci--gucci-bloom-intense', 'b' => 'Gucci', 'n' => 'Gucci Bloom Intense', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral blanc', 'x' => 'Eau de Parfum Intense', 't' => array('Tubéreuse'), 'c' => array('Jasmin sambac', 'Fleur de chèvrefeuille'), 'f' => array('Racine d\'iris', 'Bois de santal'), 'd' => 'Un mur de fleurs blanches vertes et enivrantes, tubéreuse en tête.'),
		array('s' => 'gucci--moonlight-serenade', 'b' => 'Gucci', 'n' => 'Moonlight Serenade', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Prune', 'Bergamote'), 'c' => array('Rose', 'Fleur d\'oranger'), 'f' => array('Patchouli', 'Vanille', 'Musc'), 'd' => 'Une rose-prune veloutée et nocturne, sur un patchouli vanillé.'),
		array('s' => 'gucci--gucci-bloom', 'b' => 'Gucci', 'n' => 'Gucci Bloom', 'pr' => '389 DH', 'g' => 'Femme', 'fam' => 'Floral blanc', 'x' => 'Eau de Parfum', 't' => array('Fleur de tubéreuse'), 'c' => array('Jasmin sambac', 'Chèvrefeuille'), 'f' => array('Racine d\'iris'), 'd' => 'Un mur de fleurs blanches, tubéreuse en tête, sans fruit ni sucre pour l\'adoucir.'),
		array('s' => 'guerlain--habit-rouge-rouge-prive', 'b' => 'Guerlain', 'n' => 'Habit Rouge Rouge Privé', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Ambré épicé', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Safran', 'Cannelle'), 'c' => array('Rose', 'Cuir'), 'f' => array('Vanille', 'Fève tonka', 'Bois ambré'), 'd' => 'L\'élégance cuir-vanille d\'Habit Rouge, épicée de safran et de cannelle.'),
		array('s' => 'guerlain--la-petite-robe-noire-edp', 'b' => 'Guerlain', 'n' => 'La Petite Robe Noire EDP', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral fruité gourmand', 'x' => 'Eau de Parfum', 't' => array('Cerise noire', 'Amande', 'Bergamote'), 'c' => array('Rose', 'Réglisse'), 'f' => array('Fève tonka', 'Vanille', 'Thé noir', 'Patchouli'), 'd' => 'Une cerise noire liquoreuse et pralinée, chic et espiègle.'),
		array('s' => 'guerlain--mon-guerlain', 'b' => 'Guerlain', 'n' => 'Mon Guerlain', 'pr' => '419 DH', 'g' => 'Femme', 'fam' => 'Ambré floral', 'x' => 'Eau de Parfum', 't' => array('Lavande de Carla', 'Bergamote'), 'c' => array('Jasmin sambac', 'Iris'), 'f' => array('Vanille de Tahiti', 'Bois de santal', 'Coumarine'), 'd' => 'Une lavande adoucie et une vanille de Tahiti crémeuse, moderne et solaire.'),
		array('s' => 'hermes--terre-dhermes-edp-intense', 'b' => 'Hermès', 'n' => 'Terre d\'Hermès EDP Intense', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Boisé minéral', 'x' => 'Eau de Parfum Intense', 't' => array('Orange', 'Pamplemousse', 'Poivre'), 'c' => array('Géranium', 'Silex'), 'f' => array('Vétiver', 'Cèdre', 'Benjoin'), 'd' => 'L\'accord terre-agrume-silex de Terre d\'Hermès, plus dense et plus vétiver.'),
		array('s' => 'hugo-boss--boss-bottled-elixir', 'b' => 'Hugo Boss', 'n' => 'Boss Bottled Elixir', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Boisé épicé', 'x' => 'Parfum Intense', 't' => array('Cannelle', 'Poivre'), 'c' => array('Bois de cèdre', 'Lavande'), 'f' => array('Vétiver', 'Bois ambré', 'Cuir'), 'd' => 'Le Boss Bottled de toujours, resserré et poivré, sillage boisé sec.'),
		array('s' => 'hugo-boss--boss-bottled-unlimited', 'b' => 'Hugo Boss', 'n' => 'Boss Bottled Unlimited', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Boisé fruité', 'x' => 'Eau de Toilette', 't' => array('Pomme verte', 'Gingembre'), 'c' => array('Fleur d\'oranger', 'Cannelle'), 'f' => array('Bois santal', 'Musc'), 'd' => 'La pomme-cannelle de Boss Bottled dynamisée d\'un gingembre pétillant.'),
		array('s' => 'hugo-boss--bottled', 'b' => 'Hugo Boss', 'n' => 'Bottled', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Boisé épicé', 'x' => 'Eau de Toilette', 't' => array('Pomme', 'Bergamote', 'Citron'), 'c' => array('Cannelle', 'Œillet', 'Bois de santal'), 'f' => array('Vétiver', 'Cèdre', 'Vanille'), 'd' => 'Le boisé-pomme du bureau par excellence : net, chaleureux, consensuel.'),
		array('s' => 'hugo-boss--bottled-night', 'b' => 'Hugo Boss', 'n' => 'Bottled Night', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Boisé aromatique', 'x' => 'Eau de Toilette', 't' => array('Lavande', 'Bergamote'), 'c' => array('Cardamome', 'Bouleau'), 'f' => array('Musc', 'Bois santal', 'Cèdre'), 'd' => 'La version nocturne de Bottled, plus sèche et plus cuirée de bouleau.'),
		array('s' => 'hugo-boss--boss-bottled-infinite', 'b' => 'Hugo Boss', 'n' => 'Boss Bottled Infinite', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Boisé épicé', 'x' => 'Eau de Parfum', 't' => array('Pomme', 'Mandarine'), 'c' => array('Lavande', 'Patchouli', 'Cèdre'), 'f' => array('Vétiver', 'Musc', 'Santal'), 'd' => 'La pomme de Bottled sur un vétiver plus sec : le costume du lundi, en mieux coupé.'),
		array('s' => 'jean-paul-gaultier--gaultier-divine-edp', 'b' => 'Jean Paul Gaultier', 'n' => 'Gaultier Divine EDP', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral gourmand', 'x' => 'Eau de Parfum', 't' => array('Aldéhydes', 'Notes marines'), 'c' => array('Fleur de sel', 'Néroli'), 'f' => array('Meringue', 'Musc', 'Bois de santal'), 'd' => 'Un floral aldéhydé céleste qui fond sur une meringue salée et un musc doux.'),
		array('s' => 'jean-paul-gaultier--la-belle-le-parfum', 'b' => 'Jean Paul Gaultier', 'n' => 'La Belle Le Parfum', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Oriental vanillé', 'x' => 'Eau de Parfum Intense', 't' => array('Poire', 'Bergamote'), 'c' => array('Vanille', 'Jasmin'), 'f' => array('Bois de santal', 'Fève tonka', 'Vétiver'), 'd' => 'La Belle réchauffée : poire liquoreuse et vanille dense sur bois toastés.'),
		array('s' => 'jean-paul-gaultier--le-beau-le-parfum', 'b' => 'Jean Paul Gaultier', 'n' => 'Le Beau Le Parfum', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Boisé ambré', 'x' => 'Eau de Parfum Intense', 't' => array('Bergamote', 'Gingembre'), 'c' => array('Noix de coco', 'Accord tiaré'), 'f' => array('Cèdre', 'Bois ambré', 'Fève tonka'), 'd' => 'Une noix de coco boisée et solaire, virile, sur un cèdre profond.'),
		array('s' => 'jean-paul-gaultier--le-male-elixir', 'b' => 'Jean Paul Gaultier', 'n' => 'Le Male Elixir', 'pr' => '319 DH', 'g' => 'Homme', 'fam' => 'Oriental vanillé', 'x' => 'Elixir', 't' => array('Lavande', 'Menthe'), 'c' => array('Vanille', 'Benjoin'), 'f' => array('Miel', 'Fève tonka', 'Tabac'), 'd' => 'Une chaleur incandescente où la lavande fondante rencontre le miel et le tabac.'),
		array('s' => 'jean-paul-gaultier--le-male-elixir-absolu', 'b' => 'Jean Paul Gaultier', 'n' => 'Le Male Elixir Absolu', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Oriental vanillé', 'x' => 'Elixir', 't' => array('Lavande', 'Menthe'), 'c' => array('Vanille', 'Benjoin'), 'f' => array('Miel', 'Tabac', 'Fève tonka'), 'd' => 'Un élixir magnétique aux notes profondes et gourmandes, miel et tabac en fond.'),
		array('s' => 'jean-paul-gaultier--le-male-le-parfum', 'b' => 'Jean Paul Gaultier', 'n' => 'Le Male Le Parfum', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Ambré', 'x' => 'Parfum Intense', 't' => array('Cardamome', 'Bergamote'), 'c' => array('Iris', 'Lavande'), 'f' => array('Vanille', 'Bois ambré', 'Fève tonka'), 'd' => 'La menthe-vanille de Le Male transformée en ambre lisse et cardamome.'),
		array('s' => 'jean-paul-gaultier--le-male-lover', 'b' => 'Jean Paul Gaultier', 'n' => 'Le Male Lover', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Oriental vanillé', 'x' => 'Eau de Parfum', 't' => array('Gingembre confit', 'Bergamote'), 'c' => array('Ananas', 'Accord metal chaud'), 'f' => array('Vanille', 'Bois de cachemire'), 'd' => 'Un gingembre confit juteux qui glisse vers une vanille boisée addictive.'),
		array('s' => 'jean-paul-gaultier--scandal-edp-pour-femme', 'b' => 'Jean Paul Gaultier', 'n' => 'Scandal EDP Pour Femme', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral gourmand', 'x' => 'Eau de Parfum', 't' => array('Miel', 'Orange sanguine', 'Mandarine'), 'c' => array('Fleur de miel', 'Gardénia', 'Jasmin'), 'f' => array('Cire d\'abeille', 'Patchouli', 'Caramel'), 'd' => 'Un miel floral opulent, patchouli net, sillage puissant et sucré.'),
		array('s' => 'jean-paul-gaultier--scandal-le-parfum', 'b' => 'Jean Paul Gaultier', 'n' => 'Scandal Le Parfum', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral ambré gourmand', 'x' => 'Parfum', 't' => array('Fleur d\'oranger', 'Bergamote'), 'c' => array('Tubéreuse', 'Jasmin'), 'f' => array('Vanille', 'Caramel', 'Fève tonka'), 'd' => 'Scandal recentré sur la vanille et le caramel, plus rond, moins miellé.'),
		array('s' => 'jean-paul-gaultier--scandal-pour-homme-absolu', 'b' => 'Jean Paul Gaultier', 'n' => 'Scandal Pour Homme Absolu', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Ambré aromatique', 'x' => 'Parfum', 't' => array('Menthe', 'Sauge', 'Absinthe'), 'c' => array('Lavande', 'Cannelle'), 'f' => array('Vanille', 'Fève tonka', 'Bois ambré'), 'd' => 'Un aromatique frais-chaud, herbes vertes en tête, vanille tonka en fond.'),
		array('s' => 'jean-paul-gaultier--scandal-pour-homme-intense', 'b' => 'Jean Paul Gaultier', 'n' => 'Scandal Pour Homme Intense', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Ambré épicé', 'x' => 'Eau de Parfum Intense', 't' => array('Poivre', 'Bergamote'), 'c' => array('Cannelle', 'Miel'), 'f' => array('Vanille', 'Bois ambré', 'Fève tonka'), 'd' => 'Le Scandal masculin épaissi de miel et de cannelle, plus sombre et sucré.'),
		array('s' => 'jean-paul-gaultier--le-beau-paradise-garden', 'b' => 'Jean Paul Gaultier', 'n' => 'Le Beau Paradise Garden', 'pr' => '389 DH', 'g' => 'Homme', 'fam' => 'Boisé fruité', 'x' => 'Eau de Parfum', 't' => array('Ananas', 'Bergamote'), 'c' => array('Noix de coco', 'Figue'), 'f' => array('Bois de santal', 'Musc', 'Ambre'), 'd' => 'Une noix de coco solaire et un ananas mûr sur un santal crémeux : vacances en flacon.'),
		array('s' => 'kayali--capri-lemon-sugar-14', 'b' => 'Kayali', 'n' => 'Capri — Lemon Sugar 14', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Hespéridé gourmand', 'x' => 'Eau de Parfum', 't' => array('Citron de Sicile', 'Bergamote'), 'c' => array('Fleur d\'oranger', 'Néroli'), 'f' => array('Sucre glace', 'Musc', 'Vanille'), 'd' => 'Un citron confit et sucré, gourmand mais lumineux, comme un limoncello glacé.'),
		array('s' => 'kayali--deja-vu-white-flower-57', 'b' => 'Kayali', 'n' => 'Deja Vu — White Flower 57', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral blanc', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Poivre rose'), 'c' => array('Fleur d\'oranger', 'Jasmin', 'Tubéreuse'), 'f' => array('Ambre', 'Musc', 'Bois de santal'), 'd' => 'Un bouquet de fleurs blanches crémeuses sur un ambre doux et musqué.'),
		array('s' => 'kayali--eden-juicy-apple-01', 'b' => 'Kayali', 'n' => 'Eden — Juicy Apple 01', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Fruité floral', 'x' => 'Eau de Parfum', 't' => array('Pomme rouge', 'Bergamote'), 'c' => array('Jasmin', 'Rose'), 'f' => array('Musc', 'Bois de cèdre', 'Vanille'), 'd' => 'Une pomme rouge croquante et juteuse sur un cœur floral discret.'),
		array('s' => 'kayali--eden-sparkling-lychee-39', 'b' => 'Kayali', 'n' => 'Eden — Sparkling Lychee 39', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Fruité floral', 'x' => 'Eau de Parfum', 't' => array('Litchi', 'Bergamote'), 'c' => array('Rose', 'Freesia'), 'f' => array('Musc blanc', 'Bois blond'), 'd' => 'Un litchi pétillant et rosé, frais et pulpeux, très facile à porter.'),
		array('s' => 'kayali--lovefest-burning-cherry-48', 'b' => 'Kayali', 'n' => 'Lovefest — Burning Cherry 48', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Fruité gourmand', 'x' => 'Eau de Parfum', 't' => array('Cerise noire', 'Poivre rose'), 'c' => array('Amande', 'Fleur de cerisier'), 'f' => array('Vanille', 'Bois de santal', 'Tonka'), 'd' => 'Une cerise noire fumée et pralinée, sombre, addictive, un peu vénéneuse.'),
		array('s' => 'kayali--marrakesh-orange-blossom-24', 'b' => 'Kayali', 'n' => 'Marrakesh — Orange Blossom 24', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral blanc', 'x' => 'Eau de Parfum', 't' => array('Fleur d\'oranger', 'Néroli'), 'c' => array('Jasmin', 'Fleur de café'), 'f' => array('Musc', 'Vanille', 'Bois ambré'), 'd' => 'Une fleur d\'oranger opulente et miellée, chaude comme un soir marocain.'),
		array('s' => 'kayali--oudgasm-rose-oud-16-intense', 'b' => 'Kayali', 'n' => 'Oudgasm — Rose Oud 16 Intense', 'pr' => '369 DH', 'g' => 'Mixte', 'fam' => 'Boisé oriental', 'x' => 'Eau de Parfum Intense', 't' => array('Safran', 'Rose'), 'c' => array('Oud', 'Rose de Damas'), 'f' => array('Ambre', 'Bois de santal', 'Patchouli'), 'd' => 'Une rose de Damas sombre enroulée autour d\'un oud safrané et ambré.'),
		array('s' => 'kayali--vanilla-28', 'b' => 'Kayali', 'n' => 'Vanilla 28', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Ambré vanillé', 'x' => 'Eau de Parfum', 't' => array('Vanille de Madagascar', 'Fleur d\'oranger', 'Safran'), 'c' => array('Jasmin', 'Tonka'), 'f' => array('Bois de santal', 'Musc', 'Ambre brun'), 'd' => 'La vanille culte de Kayali : boisée, un peu boozy, jamais écœurante.'),
		array('s' => 'kayali--vanilla-candy-rock-sugar-42', 'b' => 'Kayali', 'n' => 'Vanilla Candy — Rock Sugar 42', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Gourmand', 'x' => 'Eau de Parfum', 't' => array('Sucre candi', 'Bergamote'), 'c' => array('Vanille', 'Fleur d\'oranger'), 'f' => array('Caramel', 'Musc', 'Tonka'), 'd' => 'Un bonbon à la vanille et au sucre cristallisé, franchement gourmand.'),
		array('s' => 'kayali--yum-boujee-marshmallow-81', 'b' => 'Kayali', 'n' => 'Yum — Boujee Marshmallow 81', 'pr' => '389 DH', 'g' => 'Femme', 'fam' => 'Gourmand', 'x' => 'Eau de Parfum', 't' => array('Guimauve', 'Poire'), 'c' => array('Fleur d\'oranger', 'Vanille'), 'f' => array('Musc', 'Bois de santal', 'Caramel'), 'd' => 'Une guimauve moelleuse et sucrée, cocon gourmand poudré de vanille.'),
		array('s' => 'kayali--yum-pistachio-gelato-33', 'b' => 'Kayali', 'n' => 'Yum — Pistachio Gelato 33', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Gourmand', 'x' => 'Eau de Parfum', 't' => array('Pistache', 'Amande'), 'c' => array('Crème glacée', 'Fleur d\'oranger'), 'f' => array('Vanille', 'Musc', 'Fève tonka'), 'd' => 'Une glace à la pistache crémeuse et légèrement salée, dessert en flacon.'),
		array('s' => 'kayali--utopia-vanilla-coco-21', 'b' => 'Kayali', 'n' => 'Utopia — Vanilla Coco 21', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Ambré gourmand', 'x' => 'Eau de Parfum', 't' => array('Noix de coco', 'Bergamote'), 'c' => array('Fleur de tiaré', 'Vanille'), 'f' => array('Bois de santal', 'Musc', 'Ambre'), 'd' => 'Une noix de coco crémeuse et solaire sur une vanille boisée de vacances.'),
		array('s' => 'lacoste--booster-edt', 'b' => 'Lacoste', 'n' => 'Booster EDT', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Aromatique fruité', 'x' => 'Eau de Toilette', 't' => array('Menthe', 'Mandarine', 'Pomme'), 'c' => array('Lavande', 'Fleur d\'oranger'), 'f' => array('Bois de santal', 'Musc'), 'd' => 'Un coup de menthe fraîche et de pomme verte, énergique et sans détour.'),
		array('s' => 'lacoste--essential-edt', 'b' => 'Lacoste', 'n' => 'Essential EDT', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Boisé fruité', 'x' => 'Eau de Toilette', 't' => array('Framboise noire', 'Cactus', 'Bergamote'), 'c' => array('Cèdre', 'Cacao', 'Gingembre'), 'f' => array('Bois blonds', 'Ambre'), 'd' => 'Une framboise noire boisée et un peu verte, discret et propre.'),
		array('s' => 'lancome--idole-lintense', 'b' => 'Lancôme', 'n' => 'Idôle L\'Intense', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral ambré', 'x' => 'Eau de Parfum Intense', 't' => array('Bergamote', 'Poivre rose'), 'c' => array('Rose de Damas', 'Jasmin'), 'f' => array('Vanille', 'Bois de santal', 'Patchouli'), 'd' => 'La rose propre d\'Idôle réchauffée d\'une vanille dense et d\'un patchouli net.'),
		array('s' => 'lancome--la-nuit-tresor-le-parfum', 'b' => 'Lancôme', 'n' => 'La Nuit Trésor Le Parfum', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Ambré gourmand', 'x' => 'Parfum', 't' => array('Litchi', 'Bergamote'), 'c' => array('Rose', 'Fleur d\'oranger'), 'f' => array('Vanille noire', 'Fève tonka', 'Praline', 'Patchouli'), 'd' => 'Une rose noire pralinée et liquoreuse, très concentrée, sillage de nuit.'),
		array('s' => 'lancome--la-vie-est-belle-lextrait', 'b' => 'Lancôme', 'n' => 'La Vie est Belle L\'Extrait', 'pr' => '409 DH', 'g' => 'Femme', 'fam' => 'Floral gourmand', 'x' => 'Extrait de Parfum', 't' => array('Cassis', 'Poire'), 'c' => array('Iris', 'Jasmin', 'Fleur d\'oranger'), 'f' => array('Praline', 'Vanille', 'Patchouli', 'Fève tonka'), 'd' => 'L\'iris-praliné de La Vie est Belle poussé à son maximum de densité.'),
		array('s' => 'lancome--tresor-in-love-edp', 'b' => 'Lancôme', 'n' => 'Trésor In Love EDP', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Poire', 'Bergamote', 'Notes vertes'), 'c' => array('Rose', 'Fleur d\'oranger', 'Pivoine'), 'f' => array('Musc', 'Bois blond'), 'd' => 'Un floral tendre et printanier, rose-pivoine sur poire fraîche.'),
		array('s' => 'lancome--la-vie-est-belle', 'b' => 'Lancôme', 'n' => 'La Vie est Belle', 'pr' => '429 DH', 'g' => 'Femme', 'fam' => 'Floral gourmand', 'x' => 'Eau de Parfum', 't' => array('Cassis', 'Poire'), 'c' => array('Iris', 'Jasmin', 'Fleur d\'oranger'), 'f' => array('Praline', 'Vanille', 'Patchouli', 'Fève tonka'), 'd' => 'L\'iris et la praline, la gourmandise la plus vendue de France, sur un patchouli net.'),
		array('s' => 'louis-vuitton--imagination', 'b' => 'Louis Vuitton', 'n' => 'Imagination', 'pr' => '619 DH', 'g' => 'Homme', 'fam' => 'Hespéridé boisé', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Mandarine', 'Orange', 'Néroli'), 'c' => array('Thé noir', 'Gingembre'), 'f' => array('Ambre', 'Bois de santal'), 'd' => 'Un agrume-thé lumineux et racé, gingembre vif sur un ambre soyeux.'),
		array('s' => 'maison-francis-kurkdjian--baccarat-rouge-540', 'b' => 'Maison Francis Kurkdjian', 'n' => 'Baccarat Rouge 540', 'pr' => '359 DH', 'g' => 'Mixte', 'fam' => 'Ambré floral', 'x' => 'Eau de Parfum', 't' => array('Safran', 'Jasmin'), 'c' => array('Accord ambre gris', 'Bois de cèdre'), 'f' => array('Résine de sapin', 'Musc blanc'), 'd' => 'L\'accord sucré-minéral le plus reconnaissable du moment, safran et bois ambré.'),
		array('s' => 'maison-francis-kurkdjian--oud-silk-mood-extrait-de-parfum', 'b' => 'Maison Francis Kurkdjian', 'n' => 'Oud Silk Mood Extrait de Parfum', 'pr' => '419 DH', 'g' => 'Mixte', 'fam' => 'Boisé oriental', 'x' => 'Extrait de Parfum', 't' => array('Rose de Bulgarie', 'Rose de Turquie'), 'c' => array('Oud'), 'f' => array('Bois de santal', 'Vétiver', 'Benjoin'), 'd' => 'Une rose de rose et un oud lisse comme de la soie, opulents et sereins.'),
		array('s' => 'montblanc--explorer-extreme', 'b' => 'Montblanc', 'n' => 'Explorer Extreme', 'pr' => '389 DH', 'g' => 'Homme', 'fam' => 'Boisé aromatique', 'x' => 'Parfum', 't' => array('Bergamote', 'Poivre rose'), 'c' => array('Lavande', 'Vétiver'), 'f' => array('Patchouli', 'Cuir', 'Ambre'), 'd' => 'Un vétiver cuiré et poivré, sobre, taillé pour le bureau comme pour la route.'),
		array('s' => 'moschino--toy-2-bubble-gum', 'b' => 'Moschino', 'n' => 'Toy 2 Bubble Gum', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Fruité gourmand', 'x' => 'Eau de Toilette', 't' => array('Chewing-gum', 'Mandarine', 'Cassis'), 'c' => array('Frangipanier', 'Pétales de rose'), 'f' => array('Musc', 'Bois de santal'), 'd' => 'Un accord chewing-gum assumé, fruité rose et régressif, jamais sérieux.'),
		array('s' => 'moschino--toy-boy', 'b' => 'Moschino', 'n' => 'Toy Boy', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Boisé épicé', 'x' => 'Eau de Parfum', 't' => array('Poivre rose', 'Poivre noir', 'Baies roses'), 'c' => array('Rose', 'Muguet', 'Magnolia'), 'f' => array('Cèdre', 'Bois de gaïac', 'Patchouli', 'Cuir'), 'd' => 'Une rose poivrée et boisée, chic et un peu insolente, portée par un homme.'),
		array('s' => 'narciso-rodriguez--fleur-musc-for-her', 'b' => 'Narciso Rodriguez', 'n' => 'Fleur Musc for Her', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral musqué', 'x' => 'Eau de Parfum', 't' => array('Poivre rose'), 'c' => array('Rose'), 'f' => array('Musc', 'Patchouli', 'Bois ambré'), 'd' => 'Une rose musquée et poudrée, tiède contre la peau, discrète et tenace.'),
		array('s' => 'narciso-rodriguez--for-her', 'b' => 'Narciso Rodriguez', 'n' => 'For Her', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral musqué chypré', 'x' => 'Eau de Toilette', 't' => array('Fleur d\'oranger', 'Osmanthus'), 'c' => array('Musc', 'Rose', 'Ambre'), 'f' => array('Patchouli', 'Vétiver', 'Vanille'), 'd' => 'Le musc chypré signature de Narciso, sensuel, sombre et légèrement fumé.'),
		array('s' => 'narciso-rodriguez--for-her-edp', 'b' => 'Narciso Rodriguez', 'n' => 'For Her EDP', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Floral musqué', 'x' => 'Eau de Parfum', 't' => array('Musc', 'Fleur d\'oranger'), 'c' => array('Rose', 'Osmanthus'), 'f' => array('Patchouli', 'Bois précieux', 'Ambre'), 'd' => 'La version parfum du musc culte, plus dense, plus florale, plus profonde.'),
		array('s' => 'narciso-rodriguez--musc-noir-for-her', 'b' => 'Narciso Rodriguez', 'n' => 'Musc Noir For Her', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Floral musqué ambré', 'x' => 'Eau de Parfum', 't' => array('Prune', 'Musc'), 'c' => array('Fleur de datura', 'Jasmin'), 'f' => array('Musc noir', 'Bois de santal', 'Ambre'), 'd' => 'Un musc noir plus charnu et fruité de prune, chaud et légèrement narcotique.'),
		array('s' => 'narciso-rodriguez--musc-noir-rose-for-her', 'b' => 'Narciso Rodriguez', 'n' => 'Musc Noir Rose For Her', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral musqué', 'x' => 'Eau de Parfum', 't' => array('Poire', 'Poivre rose'), 'c' => array('Rose', 'Musc'), 'f' => array('Musc noir', 'Patchouli', 'Bois ambré'), 'd' => 'Le Musc Noir revisité en rose-poire, plus fleuri et plus lumineux.'),
		array('s' => 'narciso-rodriguez--narciso-edp-poudree', 'b' => 'Narciso Rodriguez', 'n' => 'Narciso EDP Poudrée', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Floral poudré', 'x' => 'Eau de Parfum', 't' => array('Fleur de tubéreuse'), 'c' => array('Musc', 'Fleur d\'oranger'), 'f' => array('Bois de cèdre', 'Vétiver', 'Musc blanc'), 'd' => 'Une tubéreuse poudrée et crémeuse, très douce, presque cosmétique.'),
		array('s' => 'narciso-rodriguez--narciso-edp-rouge', 'b' => 'Narciso Rodriguez', 'n' => 'Narciso EDP Rouge', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral boisé', 'x' => 'Eau de Parfum', 't' => array('Rose bulgare', 'Bois de rose'), 'c' => array('Musc', 'Iris'), 'f' => array('Cèdre', 'Vétiver', 'Ambre'), 'd' => 'Un musc plus boisé et charpenté, rose et cèdre, sillage affirmé.'),
		array('s' => 'nishane--hacivat', 'b' => 'Nishane', 'n' => 'Hacivat', 'pr' => '459 DH', 'g' => 'Mixte', 'fam' => 'Chypré fruité', 'x' => 'Extrait de Parfum', 't' => array('Ananas', 'Pamplemousse', 'Bergamote'), 'c' => array('Cèdre', 'Bois de gaïac', 'Patchouli'), 'f' => array('Mousse de chêne', 'Musc', 'Ambre'), 'd' => 'Un ananas boisé et raffiné, dans l\'esprit d\'Aventus mais plus vert et sec.'),
		array('s' => 'parfums-de-marly--delina-exclusif', 'b' => 'Parfums de Marly', 'n' => 'Delina Exclusif', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Extrait de Parfum', 't' => array('Litchi', 'Bergamote', 'Nèfle'), 'c' => array('Rose turque', 'Pivoine', 'Muguet'), 'f' => array('Vanille', 'Bois de oud', 'Musc', 'Cachemire'), 'd' => 'La rose-litchi de Delina rendue plus vanillée et enveloppante, très concentrée.'),
		array('s' => 'parfums-de-marly--layton', 'b' => 'Parfums de Marly', 'n' => 'Layton', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Ambré floral', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Mandarine', 'Pomme', 'Lavande'), 'c' => array('Géranium', 'Jasmin', 'Violette'), 'f' => array('Vanille', 'Bois de santal', 'Poivre', 'Cardamome'), 'd' => 'Une pomme-lavande élégante sur une vanille crémeuse, polyvalent et racé.'),
		array('s' => 'parfums-de-marly--oriana-royal-essence', 'b' => 'Parfums de Marly', 'n' => 'Oriana Royal Essence', 'pr' => '339 DH', 'g' => 'Femme', 'fam' => 'Floral fruité musqué', 'x' => 'Eau de Parfum', 't' => array('Cassis', 'Rhubarbe', 'Bergamote'), 'c' => array('Fleur de coton', 'Jasmin', 'Miel'), 'f' => array('Musc blanc', 'Bois de santal', 'Vanille'), 'd' => 'Un fruité rose et laiteux, moderne et doudou, autour d\'une fleur de coton.'),
		array('s' => 'parfums-de-marly--palatine', 'b' => 'Parfums de Marly', 'n' => 'Palatine', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral chypré', 'x' => 'Eau de Parfum', 't' => array('Poivre rose', 'Cardamome', 'Prune'), 'c' => array('Tubéreuse', 'Iris', 'Fleur d\'oranger'), 'f' => array('Patchouli', 'Vanille', 'Musc', 'Ambre'), 'd' => 'Une tubéreuse-prune opulente, chypre moderne au sillage aristocratique.'),
		array('s' => 'parfums-de-marly--delina', 'b' => 'Parfums de Marly', 'n' => 'Delina', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral rosé', 'x' => 'Eau de Parfum', 't' => array('Litchi', 'Rhubarbe', 'Bergamote'), 'c' => array('Rose de Turquie', 'Pivoine', 'Muguet'), 'f' => array('Vanille', 'Cachemire', 'Musc', 'Vétiver'), 'd' => 'La rose-litchi qui a fait la maison : fruitée, poudrée, impossible à confondre.'),
		array('s' => 'parfums-de-marly--delina-royal-essence', 'b' => 'Parfums de Marly', 'n' => 'Delina Royal Essence', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Floral rosé', 'x' => 'Eau de Parfum', 't' => array('Litchi', 'Bergamote'), 'c' => array('Rose', 'Pivoine'), 'f' => array('Vanille', 'Musc', 'Bois de cachemire'), 'd' => 'Delina dans sa version la plus dense, la rose serrée sur un fond vanillé.'),
		array('s' => 'parfums-de-marly--valaya-exclusif', 'b' => 'Parfums de Marly', 'n' => 'Valaya Exclusif', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral musqué', 'x' => 'Parfum', 't' => array('Bergamote', 'Poire'), 'c' => array('Fleur d\'oranger', 'Jasmin'), 'f' => array('Musc blanc', 'Bois blond', 'Ambrette'), 'd' => 'Le propre absolu : un musc de linge frais, lumineux, qui ne crie jamais.'),
		array('s' => 'prada--carbon-luna-rossa-edt', 'b' => 'Prada', 'n' => 'Carbon Luna Rossa EDT', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Aromatique métallique', 'x' => 'Eau de Toilette', 't' => array('Bergamote', 'Poivre', 'Accord métallique'), 'c' => array('Lavande', 'Sauge'), 'f' => array('Ambre', 'Patchouli', 'Bois de cèdre'), 'd' => 'Un aromatique froid et minéral, lavande sur accord métal et patchouli.'),
		array('s' => 'prada--paradigme', 'b' => 'Prada', 'n' => 'Paradigme', 'pr' => '369 DH', 'g' => 'Mixte', 'fam' => 'Floral musqué', 'x' => 'Eau de Parfum', 't' => array('Mandarine', 'Poivre rose'), 'c' => array('Néroli', 'Fleur d\'oranger'), 'f' => array('Musc', 'Ambre', 'Bois blond'), 'd' => 'Un floral solaire et propre, néroli lumineux enveloppé de musc doux.'),
		array('s' => 'prada--paradoxe-intense', 'b' => 'Prada', 'n' => 'Paradoxe Intense', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral ambré', 'x' => 'Eau de Parfum Intense', 't' => array('Néroli', 'Bergamote'), 'c' => array('Fleur d\'oranger', 'Jasmin'), 'f' => array('Vanille', 'Ambre', 'Musc'), 'd' => 'La fleur d\'oranger de Paradoxe alourdie de vanille et d\'ambre, plus nocturne.'),
		array('s' => 'prada--paradoxe-radical-essence', 'b' => 'Prada', 'n' => 'Paradoxe Radical Essence', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral musqué', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Poivre rose'), 'c' => array('Néroli', 'Fleur d\'oranger', 'Jasmin'), 'f' => array('Musc blanc', 'Bois ambré', 'Vanille'), 'd' => 'Un néroli net et musqué, minimaliste et propre, sillage seconde peau.'),
		array('s' => 'rabanne--1-million-parfum', 'b' => 'Rabanne', 'n' => '1 Million Parfum', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Ambré épicé cuir', 'x' => 'Parfum', 't' => array('Cannelle', 'Cardamome', 'Pamplemousse'), 'c' => array('Rose', 'Cuir'), 'f' => array('Ambre', 'Fève tonka', 'Bois blonds'), 'd' => 'Le 1 Million originel rendu plus cuiré et plus épicé, sillage massif.'),
		array('s' => 'rabanne--1-million-royal', 'b' => 'Rabanne', 'n' => '1 Million Royal', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Ambré aromatique', 'x' => 'Parfum', 't' => array('Absinthe', 'Menthe glaciale'), 'c' => array('Bois aromatiques'), 'f' => array('Ambre doré', 'Résines', 'Fève tonka'), 'd' => 'Une menthe glacée qui s\'écrase sur un ambre doré massif, frais puis chaud.'),
		array('s' => 'rabanne--1-million', 'b' => 'Rabanne', 'n' => '1 Million', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Ambré épicé', 'x' => 'Eau de Toilette', 't' => array('Pamplemousse', 'Menthe', 'Mandarine rouge'), 'c' => array('Rose', 'Cannelle', 'Épices'), 'f' => array('Cuir blond', 'Bois ambré', 'Patchouli'), 'd' => 'La cannelle et le cuir blond du lingot d\'or : reconnaissable à trois mètres, depuis 2008.'),
		array('s' => 'rabanne--1-million-lucky', 'b' => 'Rabanne', 'n' => '1 Million Lucky', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Boisé fruité', 'x' => 'Eau de Toilette', 't' => array('Prune', 'Noisette'), 'c' => array('Rose', 'Notes vertes'), 'f' => array('Cèdre', 'Ambre', 'Bois de santal'), 'd' => 'Une prune sucrée et une noisette grillée, le 1 Million le plus tendre.'),
		array('s' => 'stephane-humbert-lucas-777--god-of-fire', 'b' => 'Stéphane Humbert Lucas 777', 'n' => 'God of Fire', 'pr' => '569 DH', 'g' => 'Mixte', 'fam' => 'Boisé ambré fruité', 'x' => 'Eau de Parfum', 't' => array('Cassis', 'Bergamote', 'Poire'), 'c' => array('Bois de santal', 'Ambre'), 'f' => array('Vanille', 'Fève tonka', 'Musc'), 'd' => 'Un cassis-poire opulent fondu dans un santal ambré très crémeux.'),
		array('s' => 'tom-ford--bitter-peach', 'b' => 'Tom Ford', 'n' => 'Bitter Peach', 'pr' => '369 DH', 'g' => 'Mixte', 'fam' => 'Fruité gourmand', 'x' => 'Eau de Parfum', 't' => array('Pêche sanguine', 'Cognac', 'Cardamome'), 'c' => array('Fleur d\'oranger', 'Rhum', 'Datura'), 'f' => array('Vanille', 'Santal', 'Cuir', 'Patchouli'), 'd' => 'Une pêche liquoreuse et boozy, opulente et collante, très Tom Ford.'),
		array('s' => 'tom-ford--black-orchid', 'b' => 'Tom Ford', 'n' => 'Black Orchid', 'pr' => '349 DH', 'g' => 'Mixte', 'fam' => 'Floral oriental', 'x' => 'Eau de Parfum', 't' => array('Truffe', 'Bergamote', 'Cassis', 'Ylang-ylang'), 'c' => array('Orchidée noire', 'Épices', 'Fleurs de fruits'), 'f' => array('Patchouli', 'Vanille', 'Encens', 'Bois de santal'), 'd' => 'Un floral sombre et vénéneux, truffe et chocolat, icône de la nuit.'),
		array('s' => 'tom-ford--fabulous', 'b' => 'Tom Ford', 'n' => 'Fabulous', 'pr' => '349 DH', 'g' => 'Mixte', 'fam' => 'Cuir ambré', 'x' => 'Eau de Parfum', 't' => array('Amande amère', 'Sauge', 'Lavande'), 'c' => array('Accord cuir', 'Fève tonka'), 'f' => array('Cuir', 'Vanille', 'Bois de cachemire', 'Ambre'), 'd' => 'Un cuir crémeux et amande, chaud et animal, dandy et provocateur.'),
		array('s' => 'tom-ford--lost-cherry', 'b' => 'Tom Ford', 'n' => 'Lost Cherry', 'pr' => '349 DH', 'g' => 'Mixte', 'fam' => 'Fruité gourmand', 'x' => 'Eau de Parfum', 't' => array('Cerise noire', 'Liqueur de cerise', 'Amande amère'), 'c' => array('Fleur de cerisier', 'Rose de Turquie', 'Jasmin'), 'f' => array('Fève tonka', 'Vanille', 'Baume du Pérou', 'Santal'), 'd' => 'Une cerise confite et sa liqueur, pralinée et sombre, follement addictive.'),
		array('s' => 'tom-ford--neroli-portofino', 'b' => 'Tom Ford', 'n' => 'Neroli Portofino', 'pr' => '349 DH', 'g' => 'Mixte', 'fam' => 'Hespéridé floral', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Mandarine', 'Citron', 'Néroli'), 'c' => array('Fleur d\'oranger', 'Lavande', 'Jasmin'), 'f' => array('Ambre', 'Musc blanc', 'Ambrette'), 'd' => 'Un néroli-agrumes éclatant de propreté, la Méditerranée en flacon de luxe.'),
		array('s' => 'tom-ford--oud-minerale', 'b' => 'Tom Ford', 'n' => 'Oud Minérale', 'pr' => '369 DH', 'g' => 'Mixte', 'fam' => 'Boisé marin', 'x' => 'Eau de Parfum', 't' => array('Notes marines', 'Poivre'), 'c' => array('Oud', 'Bois flotté'), 'f' => array('Ambre gris', 'Musc', 'Sel'), 'd' => 'Un oud iodé et salin, contre-intuitif : le désert qui rencontre l\'océan.'),
		array('s' => 'tom-ford--oud-wood', 'b' => 'Tom Ford', 'n' => 'Oud Wood', 'pr' => '349 DH', 'g' => 'Mixte', 'fam' => 'Boisé oriental', 'x' => 'Eau de Parfum', 't' => array('Oud', 'Palissandre', 'Cardamome'), 'c' => array('Bois de santal', 'Vétiver', 'Poivre de Sichuan'), 'f' => array('Fève tonka', 'Vanille', 'Ambre gris'), 'd' => 'L\'oud d\'entrée dans la niche : fumé mais lisse, tonka et vanille pour l\'apprivoiser.'),
		array('s' => 'tom-ford--rose-de-russie', 'b' => 'Tom Ford', 'n' => 'Rose De Russie', 'pr' => '349 DH', 'g' => 'Mixte', 'fam' => 'Cuir floral', 'x' => 'Eau de Parfum', 't' => array('Poivre rose', 'Rhum'), 'c' => array('Rose de Damas', 'Rose de Mai', 'Encens'), 'f' => array('Cuir', 'Patchouli', 'Musc'), 'd' => 'Une rose cuirée et poivrée, épaisse et enivrante, sombre et charnelle.'),
		array('s' => 'tom-ford--rose-prick-edp', 'b' => 'Tom Ford', 'n' => 'Rose Prick EDP', 'pr' => '349 DH', 'g' => 'Mixte', 'fam' => 'Floral épicé', 'x' => 'Eau de Parfum', 't' => array('Poivre de Sichuan', 'Poivre rose'), 'c' => array('Rose de Turquie', 'Rose de Mai', 'Rose de Bulgarie'), 'f' => array('Patchouli', 'Tonka', 'Bois de santal'), 'd' => 'Trois roses épineuses, poivrées et terreuses, un jardin sauvage en épines.'),
		array('s' => 'tom-ford--tobacco-vanille', 'b' => 'Tom Ford', 'n' => 'Tobacco Vanille', 'pr' => '369 DH', 'g' => 'Mixte', 'fam' => 'Ambré tabac', 'x' => 'Eau de Parfum', 't' => array('Feuille de tabac', 'Épices'), 'c' => array('Vanille', 'Cacao', 'Fruits secs', 'Fève tonka'), 'f' => array('Bois secs', 'Ambre'), 'd' => 'Un tabac blond noyé de vanille et de fruits confits, chaleur de fauteuil club.'),
		array('s' => 'tom-ford--vanilla-sex', 'b' => 'Tom Ford', 'n' => 'Vanilla Sex', 'pr' => '349 DH', 'g' => 'Mixte', 'fam' => 'Ambré vanillé', 'x' => 'Eau de Parfum', 't' => array('Cardamome', 'Poivre rose', 'Néroli'), 'c' => array('Fleur d\'oranger', 'Suède'), 'f' => array('Vanille de Madagascar', 'Fève tonka', 'Musc', 'Bois de santal'), 'd' => 'Une vanille suédée et poudrée, chaude et charnelle, seconde peau assumée.'),
		array('s' => 'tom-ford--ombre-leather', 'b' => 'Tom Ford', 'n' => 'Ombré Leather', 'pr' => '369 DH', 'g' => 'Mixte', 'fam' => 'Cuir épicé', 'x' => 'Eau de Parfum', 't' => array('Cardamome'), 'c' => array('Cuir', 'Jasmin sambac'), 'f' => array('Ambre', 'Mousse de chêne', 'Patchouli'), 'd' => 'Un cuir sec et fumé, à peine fleuri, qui tient du blouson autant que du parfum.'),
		array('s' => 'valentino--born-in-roma-extradose', 'b' => 'Valentino', 'n' => 'Born in Roma Extradose', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral ambré gourmand', 'x' => 'Eau de Parfum Intense', 't' => array('Bergamote', 'Cassis'), 'c' => array('Jasmin sambac', 'Fleur de vanille'), 'f' => array('Vanille', 'Bois de gaïac', 'Ambre'), 'd' => 'Le Born in Roma féminin saturé de vanille et de jasmin, sillage dense.'),
		array('s' => 'valentino--donna-born-in-roma-intense', 'b' => 'Valentino', 'n' => 'Donna Born In Roma Intense', 'pr' => '319 DH', 'g' => 'Femme', 'fam' => 'Floral ambré', 'x' => 'Eau de Parfum Intense', 't' => array('Cassis', 'Bergamote'), 'c' => array('Jasmin sambac', 'Rose'), 'f' => array('Vanille bourbon', 'Bois de cachemire'), 'd' => 'Un jasmin-cassis lumineux qui bascule sur une vanille bourbon crémeuse.'),
		array('s' => 'valentino--uomo-born-in-roma-green-stravaganza', 'b' => 'Valentino', 'n' => 'Uomo Born in Roma Green Stravaganza', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Aromatique vert', 'x' => 'Eau de Toilette', 't' => array('Bergamote', 'Feuilles de figuier', 'Menthe'), 'c' => array('Sauge', 'Genièvre'), 'f' => array('Vétiver', 'Bois de gaïac', 'Musc'), 'd' => 'Un vert vif et végétal, figuier et menthe sur un vétiver frais.'),
		array('s' => 'valentino--uomo-born-in-roma-intense', 'b' => 'Valentino', 'n' => 'Uomo Born In Roma Intense', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Ambré boisé', 'x' => 'Eau de Parfum Intense', 't' => array('Sauge', 'Bergamote'), 'c' => array('Gingembre', 'Iris', 'Fleur de vanille'), 'f' => array('Vanille', 'Bois ambré', 'Patchouli'), 'd' => 'Le Born in Roma masculin resserré autour d\'une vanille boisée virile.'),
		array('s' => 'valentino--uomo-intense', 'b' => 'Valentino', 'n' => 'Uomo Intense', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Cuir ambré', 'x' => 'Eau de Parfum', 't' => array('Bergamote de Calabre', 'Myrte'), 'c' => array('Iris', 'Cuir'), 'f' => array('Ambre', 'Vanille', 'Bois de santal'), 'd' => 'Un iris-cuir chaud et poudré, élégance italienne un peu gourmande.'),
		array('s' => 'versace--bright-crystal', 'b' => 'Versace', 'n' => 'Bright Crystal', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Toilette', 't' => array('Grenade', 'Yuzu', 'Notes glacées'), 'c' => array('Pivoine', 'Magnolia', 'Lotus'), 'f' => array('Musc', 'Bois d\'acajou', 'Ambre'), 'd' => 'Une grenade fraîche et pétillante sur un cœur de pivoine translucide.'),
		array('s' => 'versace--crystal-noir', 'b' => 'Versace', 'n' => 'Crystal Noir', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Floral oriental', 'x' => 'Eau de Toilette', 't' => array('Gingembre', 'Poivre', 'Cardamome'), 'c' => array('Gardénia', 'Fleur d\'oranger', 'Noix de coco'), 'f' => array('Ambre', 'Musc', 'Bois de santal'), 'd' => 'Un gardénia épicé et crémeux, oriental doux au sillage insistant.'),
		array('s' => 'versace--eros-edp', 'b' => 'Versace', 'n' => 'Eros EDP', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Aromatique fougère', 'x' => 'Eau de Parfum', 't' => array('Menthe', 'Citron', 'Pomme verte'), 'c' => array('Fève tonka', 'Géranium', 'Ambroxan'), 'f' => array('Vanille', 'Vétiver', 'Cèdre', 'Bois de cèdre'), 'd' => 'La menthe-vanille bleue d\'Eros, plus dense en EDP, sillage de club.'),
		array('s' => 'versace--eros-energy-pour-homme-edp', 'b' => 'Versace', 'n' => 'Eros Energy Pour Homme EDP', 'pr' => '359 DH', 'g' => 'Homme', 'fam' => 'Aromatique aquatique', 'x' => 'Eau de Parfum', 't' => array('Citron', 'Bergamote', 'Notes marines'), 'c' => array('Menthe', 'Cardamome'), 'f' => array('Ambroxan', 'Bois de cèdre', 'Musc'), 'd' => 'Un Eros plus frais et marin, agrumes salins sur ambroxan lumineux.'),
		array('s' => 'versace--eros-flame', 'b' => 'Versace', 'n' => 'Eros Flame', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Boisé aromatique', 'x' => 'Eau de Parfum', 't' => array('Orange sanguine', 'Mandarine', 'Poivre noir'), 'c' => array('Romarin', 'Géranium', 'Poivre rose'), 'f' => array('Vanille', 'Fève tonka', 'Bois de cèdre', 'Patchouli'), 'd' => 'La version chaude et agrume d\'Eros, orange sanguine sur bois vanillés.'),
		array('s' => 'versace--man-eau-fraiche-extreme', 'b' => 'Versace', 'n' => 'Man Eau Fraiche Extreme', 'pr' => '359 DH', 'g' => 'Homme', 'fam' => 'Aromatique aquatique', 'x' => 'Eau de Toilette Intense', 't' => array('Bergamote', 'Citron', 'Notes marines'), 'c' => array('Sauge', 'Cèdre bleu'), 'f' => array('Bois de rose', 'Musc', 'Ambre'), 'd' => 'Le bleu marin de Man Eau Fraîche concentré, plus tenace et plus boisé.'),
		array('s' => 'versace--dylan-blue-pour-homme', 'b' => 'Versace', 'n' => 'Dylan Blue Pour Homme', 'pr' => '389 DH', 'g' => 'Homme', 'fam' => 'Aromatique boisé', 'x' => 'Eau de Toilette', 't' => array('Bergamote', 'Pamplemousse', 'Notes aquatiques'), 'c' => array('Papyrus', 'Violette', 'Poivre noir'), 'f' => array('Musc', 'Patchouli', 'Encens'), 'd' => 'Un aquatique poivré et net, le Versace le plus porté en journée.'),
		array('s' => 'versace--dylan-blush-pour-femme', 'b' => 'Versace', 'n' => 'Dylan Blush Pour Femme', 'pr' => '389 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Framboise', 'Pamplemousse rose'), 'c' => array('Pivoine', 'Rose'), 'f' => array('Musc', 'Bois de santal'), 'd' => 'La framboise et la pivoine en version rose poudré, franche et facile.'),
		array('s' => 'versace--eros-parfum', 'b' => 'Versace', 'n' => 'Eros Parfum', 'pr' => '389 DH', 'g' => 'Homme', 'fam' => 'Boisé aromatique', 'x' => 'Parfum', 't' => array('Menthe', 'Citron', 'Poivre noir'), 'c' => array('Géranium', 'Sauge', 'Ambroxan'), 'f' => array('Vétiver', 'Patchouli', 'Cèdre', 'Fève tonka'), 'd' => 'Eros resserré autour du vétiver et de la tonka : moins sucré, plus adulte.'),
		array('s' => 'victorias-secret--bombshell', 'b' => 'Victoria\'s Secret', 'n' => 'Bombshell', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Fruit de la passion', 'Pamplemousse', 'Baies de Goji'), 'c' => array('Pivoine', 'Orchidée vanille', 'Fleur de gardénia'), 'f' => array('Musc', 'Bois', 'Ambre'), 'd' => 'Un fruité-floral solaire et bruyant, passion et pivoine, signature US.'),
		array('s' => 'victorias-secret--bombshell-seduction-edp', 'b' => 'Victoria\'s Secret', 'n' => 'Bombshell Seduction EDP', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Nectarine', 'Bergamote'), 'c' => array('Pivoine', 'Freesia'), 'f' => array('Musc', 'Praline', 'Bois blond'), 'd' => 'Le Bombshell revisité plus sucré et plus doux, nectarine et praline.'),
		array('s' => 'viktor-rolf--spicebomb-extreme', 'b' => 'Viktor&Rolf', 'n' => 'Spicebomb Extreme', 'pr' => '389 DH', 'g' => 'Homme', 'fam' => 'Ambré épicé', 'x' => 'Eau de Parfum', 't' => array('Poivre noir', 'Cannelle'), 'c' => array('Tabac', 'Cumin', 'Poivre'), 'f' => array('Vanille', 'Fève tonka'), 'd' => 'Une bombe d\'épices chaudes : poivre, cannelle et tabac sur vanille dense.'),
		array('s' => 'xerjoff--accento', 'b' => 'Xerjoff', 'n' => 'Accento', 'pr' => '389 DH', 'g' => 'Mixte', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Ananas', 'Poivre rose'), 'c' => array('Rose', 'Jasmin', 'Fleur d\'oranger'), 'f' => array('Ambre', 'Musc', 'Bois de gaïac'), 'd' => 'Un fruité-floral pétillant et raffiné, ananas juteux sur roses de Grasse.'),
		array('s' => 'xerjoff--erba-pura', 'b' => 'Xerjoff', 'n' => 'Erba Pura', 'pr' => '389 DH', 'g' => 'Mixte', 'fam' => 'Fruité ambré', 'x' => 'Eau de Parfum', 't' => array('Orange', 'Bergamote', 'Citron', 'Fruits siciliens'), 'c' => array('Fruits blancs', 'Notes gourmandes'), 'f' => array('Musc blanc', 'Ambre', 'Vanille'), 'd' => 'Un cocktail d\'agrumes et de fruits juteux sur un ambre-musc addictif.'),
		array('s' => 'xerjoff--fierezza', 'b' => 'Xerjoff', 'n' => 'Fierezza', 'pr' => '1 469 DH', 'g' => 'Mixte', 'fam' => 'Chypré vert', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Galbanum', 'Notes vertes'), 'c' => array('Iris', 'Rose', 'Géranium'), 'f' => array('Mousse de chêne', 'Vétiver', 'Musc', 'Ambre'), 'd' => 'Un chypre vert classique et fier, galbanum mordant sur mousse de chêne.'),
		array('s' => 'xerjoff--naxos', 'b' => 'Xerjoff', 'n' => 'Naxos', 'pr' => '389 DH', 'g' => 'Homme', 'fam' => 'Ambré tabac miel', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Lavande', 'Citron'), 'c' => array('Miel', 'Tabac', 'Cannelle', 'Fleur d\'oranger'), 'f' => array('Fève tonka', 'Vanille', 'Miel', 'Bois'), 'd' => 'Un tabac au miel opulent, sucré et résineux, chef-d\'œuvre gourmand de la niche.'),
		array('s' => 'xerjoff--perseveranza', 'b' => 'Xerjoff', 'n' => 'Perseveranza', 'pr' => '1 469 DH', 'g' => 'Mixte', 'fam' => 'Boisé épicé', 'x' => 'Eau de Parfum', 't' => array('Poivre', 'Bergamote', 'Safran'), 'c' => array('Rose', 'Oud', 'Cuir'), 'f' => array('Bois de santal', 'Ambre', 'Patchouli'), 'd' => 'Un boisé-cuir épicé et dense, rose et oud tenus par un santal profond.'),
		array('s' => 'xerjoff--wardasina', 'b' => 'Xerjoff', 'n' => 'Wardasina', 'pr' => '389 DH', 'g' => 'Femme', 'fam' => 'Floral fruité', 'x' => 'Eau de Parfum', 't' => array('Cassis', 'Framboise', 'Bergamote'), 'c' => array('Rose de Turquie', 'Muguet', 'Jasmin'), 'f' => array('Musc', 'Bois de santal', 'Ambre'), 'd' => 'Une rose fruitée de framboise et de cassis, éclatante et généreuse.'),
		array('s' => 'yves-saint-laurent--babycat-raw-bourbon', 'b' => 'Yves Saint Laurent', 'n' => 'Babycat Raw Bourbon', 'pr' => '519 DH', 'g' => 'Mixte', 'fam' => 'Cuir ambré', 'x' => 'Eau de Parfum', 't' => array('Rhum', 'Safran'), 'c' => array('Cuir', 'Fleur d\'oranger'), 'f' => array('Vanille bourbon', 'Fève tonka', 'Ambre'), 'd' => 'Un cuir boozy au rhum et à la vanille bourbon, chaud, animal, luxueux.'),
		array('s' => 'yves-saint-laurent--black-opium-glitter', 'b' => 'Yves Saint Laurent', 'n' => 'Black Opium Glitter', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral gourmand', 'x' => 'Eau de Parfum', 't' => array('Poire', 'Bergamote', 'Notes pétillantes'), 'c' => array('Café', 'Fleur d\'oranger', 'Jasmin'), 'f' => array('Vanille', 'Praline', 'Bois de cèdre'), 'd' => 'Le café-vanille de Black Opium relevé d\'une poire pétillante et sucrée.'),
		array('s' => 'yves-saint-laurent--black-opium-over-red', 'b' => 'Yves Saint Laurent', 'n' => 'Black Opium Over Red', 'pr' => '359 DH', 'g' => 'Femme', 'fam' => 'Floral fruité gourmand', 'x' => 'Eau de Parfum', 't' => array('Cerise', 'Poivre rose'), 'c' => array('Café', 'Fleur d\'oranger'), 'f' => array('Vanille', 'Patchouli', 'Bois de cèdre'), 'd' => 'Black Opium mordu de cerise noire, plus fruité, plus insolent.'),
		array('s' => 'yves-saint-laurent--la-nuit-de-lhomme-bleu-electrique', 'b' => 'Yves Saint Laurent', 'n' => 'La Nuit de L\'Homme Bleu Électrique', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Aromatique boisé', 'x' => 'Eau de Toilette', 't' => array('Cardamome', 'Bergamote', 'Notes glacées'), 'c' => array('Lavande', 'Géranium'), 'f' => array('Cèdre', 'Vétiver', 'Musc'), 'd' => 'La cardamome de La Nuit de L\'Homme rafraîchie d\'un souffle glacé.'),
		array('s' => 'yves-saint-laurent--la-nuit-de-lhomme-edp', 'b' => 'Yves Saint Laurent', 'n' => 'La Nuit de L\'Homme EDP', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Aromatique boisé', 'x' => 'Eau de Parfum', 't' => array('Cardamome', 'Bergamote'), 'c' => array('Lavande', 'Cèdre de Virginie'), 'f' => array('Cumin', 'Vétiver', 'Fève tonka'), 'd' => 'La séduction cardamome-cèdre en version parfum, plus ronde et plus tenace.'),
		array('s' => 'yves-saint-laurent--la-nuit-de-lhomme-le-parfum', 'b' => 'Yves Saint Laurent', 'n' => 'La Nuit de L\'Homme Le Parfum', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Ambré boisé', 'x' => 'Parfum', 't' => array('Cardamome', 'Poivre rose'), 'c' => array('Lavande', 'Rose'), 'f' => array('Bois ambré', 'Fève tonka', 'Patchouli'), 'd' => 'La Nuit de L\'Homme réchauffée d\'ambre et de patchouli, sillage du soir.'),
		array('s' => 'yves-saint-laurent--libre-edp-intense', 'b' => 'Yves Saint Laurent', 'n' => 'Libre EDP Intense', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral ambré', 'x' => 'Eau de Parfum Intense', 't' => array('Bergamote', 'Mandarine', 'Safran'), 'c' => array('Lavande', 'Fleur d\'oranger', 'Jasmin'), 'f' => array('Vanille', 'Ambre gris', 'Fève tonka', 'Bois de cèdre'), 'd' => 'La lavande-fleur d\'oranger de Libre alourdie de vanille, plus dense et sombre.'),
		array('s' => 'yves-saint-laurent--libre-labsolu-platine', 'b' => 'Yves Saint Laurent', 'n' => 'Libre L\'Absolu Platine', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Aromatique ambré', 'x' => 'Parfum', 't' => array('Bergamote', 'Lavande glacée'), 'c' => array('Fleur d\'oranger', 'Sauge'), 'f' => array('Vanille', 'Musc', 'Bois ambré'), 'd' => 'Un Libre plus froid et minéral, lavande gelée sur une vanille sèche.'),
		array('s' => 'yves-saint-laurent--libre-leau-nue', 'b' => 'Yves Saint Laurent', 'n' => 'Libre L\'Eau Nue', 'pr' => '349 DH', 'g' => 'Femme', 'fam' => 'Floral frais', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Notes vertes'), 'c' => array('Lavande', 'Fleur d\'oranger', 'Néroli'), 'f' => array('Musc blanc', 'Bois clairs'), 'd' => 'La version transparente de Libre, lavande fraîche et peau propre.'),
		array('s' => 'yves-saint-laurent--libre-le-parfum', 'b' => 'Yves Saint Laurent', 'n' => 'Libre Le Parfum', 'pr' => '339 DH', 'g' => 'Femme', 'fam' => 'Floral ambré', 'x' => 'Parfum', 't' => array('Gingembre', 'Bergamote', 'Mandarine'), 'c' => array('Lavande', 'Fleur d\'oranger', 'Jasmin'), 'f' => array('Vanille ambrée', 'Fève tonka', 'Bois de santal'), 'd' => 'Lavande et fleur d\'oranger sur une vanille ambrée, le Libre le plus chaud.'),
		array('s' => 'yves-saint-laurent--mon-paris', 'b' => 'Yves Saint Laurent', 'n' => 'Mon Paris', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Chypré fruité', 'x' => 'Eau de Parfum', 't' => array('Fraise', 'Framboise', 'Poire', 'Bergamote'), 'c' => array('Datura', 'Pivoine', 'Jasmin'), 'f' => array('Patchouli', 'Mousse de chêne', 'Musc blanc', 'Ambre'), 'd' => 'Un fruité rouge acidulé sur un patchouli net, chypre pop et romanesque.'),
		array('s' => 'yves-saint-laurent--myslf-edp', 'b' => 'Yves Saint Laurent', 'n' => 'MYSLF EDP', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Floral boisé', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Poire'), 'c' => array('Fleur d\'oranger', 'Néroli'), 'f' => array('Ambre', 'Bois de patchouli', 'Musc'), 'd' => 'Une fleur d\'oranger masculine et moderne, propre, tenue par un ambre-patchouli.'),
		array('s' => 'yves-saint-laurent--myslf-labsolu', 'b' => 'Yves Saint Laurent', 'n' => 'MYSLF L\'Absolu', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Ambré boisé', 'x' => 'Parfum', 't' => array('Bergamote', 'Cardamome'), 'c' => array('Fleur d\'oranger', 'Iris'), 'f' => array('Vanille', 'Bois ambré', 'Patchouli'), 'd' => 'MYSLF concentré et réchauffé de vanille, plus sensuel et nocturne.'),
		array('s' => 'yves-saint-laurent--myslf-le-parfum', 'b' => 'Yves Saint Laurent', 'n' => 'MYSLF Le Parfum', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Floral ambré', 'x' => 'Parfum', 't' => array('Poire', 'Bergamote', 'Cannelle'), 'c' => array('Fleur d\'oranger', 'Néroli'), 'f' => array('Fève tonka', 'Bois ambré', 'Musc'), 'd' => 'La fleur d\'oranger de MYSLF adoucie d\'une poire épicée et de tonka.'),
		array('s' => 'yves-saint-laurent--y-edp', 'b' => 'Yves Saint Laurent', 'n' => 'Y EDP', 'pr' => '319 DH', 'g' => 'Homme', 'fam' => 'Aromatique boisé', 'x' => 'Eau de Parfum', 't' => array('Bergamote', 'Gingembre', 'Sauge'), 'c' => array('Feuille de violette', 'Géranium', 'Sauge sclarée'), 'f' => array('Fève tonka', 'Bois de cèdre', 'Vétiver', 'Ambroxan'), 'd' => 'Le boisé-aromatique du bureau : sauge fraîche, cèdre net, tonka discrète.'),
		array('s' => 'yves-saint-laurent--y-eau-fraiche', 'b' => 'Yves Saint Laurent', 'n' => 'Y Eau Fraiche', 'pr' => '349 DH', 'g' => 'Homme', 'fam' => 'Aromatique aquatique', 'x' => 'Eau de Toilette', 't' => array('Bergamote', 'Notes marines', 'Pamplemousse'), 'c' => array('Sauge', 'Genièvre'), 'f' => array('Ambre gris', 'Cèdre', 'Vétiver'), 'd' => 'La version marine et légère de Y, sauge et sel sur bois clairs.'),
		array('s' => 'yves-saint-laurent--y-elixir', 'b' => 'Yves Saint Laurent', 'n' => 'Y Elixir', 'pr' => '369 DH', 'g' => 'Homme', 'fam' => 'Boisé aromatique', 'x' => 'Elixir', 't' => array('Bergamote', 'Cardamome'), 'c' => array('Lavande', 'Sauge', 'Feuille de violette'), 'f' => array('Cuir', 'Fève tonka', 'Patchouli', 'Bois de cèdre'), 'd' => 'Y poussé vers le cuir et le patchouli, plus sombre, plus dense, plus adulte.'),
		array('s' => 'yves-saint-laurent--y-le-parfum', 'b' => 'Yves Saint Laurent', 'n' => 'Y Le Parfum', 'pr' => '359 DH', 'g' => 'Homme', 'fam' => 'Aromatique ambré', 'x' => 'Parfum', 't' => array('Pomme', 'Gingembre', 'Bergamote'), 'c' => array('Sauge', 'Feuille de violette'), 'f' => array('Fève tonka', 'Cèdre', 'Vanille', 'Bois ambré'), 'd' => 'Le Y le plus chaud : pomme et sauge sur une tonka vanillée.'),
		array('s' => 'yves-saint-laurent--black-opium', 'b' => 'Yves Saint Laurent', 'n' => 'Black Opium', 'pr' => '369 DH', 'g' => 'Femme', 'fam' => 'Ambré gourmand', 'x' => 'Eau de Parfum', 't' => array('Poire', 'Poivre rose', 'Mandarine'), 'c' => array('Café', 'Fleur d\'oranger', 'Jasmin'), 'f' => array('Vanille', 'Patchouli', 'Cèdre'), 'd' => 'Le café-vanille qui a lancé la mode : nerveux en tête, cotonneux en fond.'),
		array('s' => 'yves-saint-laurent--cinema', 'b' => 'Yves Saint Laurent', 'n' => 'Cinéma', 'pr' => '389 DH', 'g' => 'Femme', 'fam' => 'Floral gourmand', 'x' => 'Eau de Parfum', 't' => array('Clémentine', 'Cyclamen'), 'c' => array('Fleur d\'oranger', 'Jasmin', 'Pivoine'), 'f' => array('Vanille', 'Amande', 'Bois de santal'), 'd' => 'Une fleur d\'oranger sucrée à l\'amande, chaleureuse et rétro, comme un velours rouge.'),
		array('s' => 'zadig-voltaire--this-is-her', 'b' => 'Zadig & Voltaire', 'n' => 'This is Her', 'pr' => '519 DH', 'g' => 'Femme', 'fam' => 'Ambré gourmand', 'x' => 'Eau de Parfum', 't' => array('Marron glacé', 'Notes lactées'), 'c' => array('Jasmin sambac', 'Rose'), 'f' => array('Bois de santal', 'Vanille', 'Patchouli', 'Musc'), 'd' => 'Une châtaigne crémeuse et lactée sur un santal vanillé, doudou chic.'),
	);
	return $cache;
}

/** Retourne la fiche d'un parfum par son slug, ou null. */
function comptoir_produit_by_slug( $slug ) {
	// Index construit une fois : la selection de la page d'accueil et les
	// « autres references de la maison » font sinon un balayage lineaire des
	// 177 entrees a chaque recherche.
	static $index = null;
	if ( null === $index ) {
		$index = array();
		foreach ( comptoir_produits() as $p ) {
			$index[ $p['s'] ] = $p;
		}
	}
	return isset( $index[ $slug ] ) ? $index[ $slug ] : null;
}

/** URL publique d'une fiche parfum. */
function comptoir_parfum_url( $slug ) {
	return home_url( '/?parfum=' . rawurlencode( $slug ) );
}

/**
 * Catalogue regroupe par maison, dans l'ordre du fichier.
 * Le filtrage « une seule maison » se fait cote navigateur (theme.js, a partir
 * de ?maison=<slug> ou #catalogue?maison=<slug>) : le catalogue complet est
 * deja dans la page, il n'y a rien a redemander au serveur.
 */
function comptoir_catalogue_par_maison() {
	static $cache = null;
	if ( null !== $cache ) {
		return $cache;
	}
	$cache = array();
	foreach ( comptoir_produits() as $p ) {
		$cache[ $p['b'] ][] = $p;
	}
	return $cache;
}

/**
 * Slug d'une maison — même règle que slugify() côté maquette :
 * sans accents, minuscules, apostrophes retirées, le reste en tirets.
 */
function comptoir_maison_slug( $name ) {
	$s = function_exists( 'remove_accents' ) ? remove_accents( (string) $name ) : (string) $name;
	$s = strtolower( $s );
	$s = str_replace( array( "'", "\xE2\x80\x99" ), '', $s );
	$s = preg_replace( '/[^a-z0-9]+/', '-', $s );
	return trim( $s, '-' );
}

